### ISSUE TITLE
Updated email template

### ISSUE THREAD

**Issue by jetlej** [jetlej/HE-6.0-Bugs#102]

**Comment by jetlej** [comment]
I forgot that I did already do this and showed you guys the template lol. Any comments now? 

http://hiexistence.com/wp-content/themes/hethen/admin/Email%20Templates/daily-test.html

@MSchirp @JonBrooksX @lostboyevsky

**Comment by JonBrooksX** [comment]
I really like it. Could we add text fade out?

**Comment by MSchirp** [comment]
Can we also have some space on top to write our messages?

**Comment by jetlej** [comment]
@JonBrooksX - Text fadeout requires CSS3 gradients, which most email clients do not support unfortunately.

@MSchirp - Yeah I kept the existing area up above, and will make some improvements to it as well

**Comment by JonBrooksX** [comment]
Okay, look good to me then.

**Comment by lostboyevsky** [comment]
looks solid

**Comment by jetlej** [comment]
@JonBrooksX @MSchirp - Please check out the test campaign I just created in Mailchimp. It uses the new template and pulls from our test site right now. I create two versions of the top 'featured' section and the bottom 'ad' section. One has an image, the other does not. That way there's no messy adding of images with weird spacing. I also make it so you can only edit the text and not change the default CSS for text :)

**Comment by MSchirp** [comment]
That's perfect :+1: 

- Do we also need weekly and monthly versions?
- Would it be much effort to get a version without the rss? For example for the insider's list, or if we ever want to send other type of e-mails just with out logo etc.

**Comment by JonBrooksX** [comment]
Just checked it out. Awesome job, J! Really do love the fact it has a QOD spot there. If the questions are juicy enough, clicking will be irresistible.

**Comment by jetlej** [comment]
@MSchirp - What do you mean 'without the logo'? I can easily make a version where you can duplicate each section as much as you want and manually insert articles. 

I built a version for Futurism where they can select the posts to include within wp-admin and they will show up in the template automatically. Could be good for weekly/monthly emails.

**Comment by MSchirp** [comment]
whoops, tried to type 'just with the logo'. 

-I like that version you just suggested. That would be amazing indeed for the weekly and monthly mails.

**Comment by jetlej** [comment]
@MSchirp, @JonBrooksX - What format do you want for weekly/monthly? X number of blog posts? Do you still want to include a spot for images in weekly/monthly?

**Comment by JonBrooksX** [comment]
I think for weekly we should show all posts but with a limit of 10. I don't see us having too much content for the weekly any time soon. I don't think it would be fair to put the highest voted content at the top because the earlier something is published the more upvotes it'll tend to have. Any ways around this? I would also like a spot for 'Question of the Week'. I'll just take the most commented QOD and include it in the weekly email. With monthly, I'd like to see a cap of 10 posts again. Not sure if I want to do a Question of the Month also, seems a bit overkill.

**Comment by MSchirp** [comment]
@jetlej I want to send out an insider list e-mail tomorrow morning 9 AM EST, also preferably just a few hours before the 6.0 launch. What template should I use in this case?

**Comment by jetlej** [comment]
@JonBrooksX - Yeah I think it makes sense to include a discussion in the weekly, but less so in the monthly. I'll include a spot for you to choose a discussion. I'm thinking max 7 posts in each email, 10 is a lot. Thoughts?

@MSchirp - I still have to make a blank email for you to use to just include text. I'll do that tonight.

**Comment by jetlej** [comment]
This is all done and tested. See http://hiexistence.com/wp-admin/admin.php?page=theme_options for the options page. Should be pretty straightforward.
