### ISSUE TITLE
I think we should have a "podcast" tab on the nav bar

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#105]
Our podcast gets little promotion on our site, and it's hard to direct people listening to the podcast to our site—we have to read out our url. If we had a visable area on the site for podcasts we could say on the podcast, as Tim Ferriss does, "go on HighExistence.com" and click "podcasts". This will also help HE fans find the podcasts and subscribe.

**Comment by jetlej** [comment]
We don't have an ongoing podcast. Until we do, it should not have a menu item.
