### ISSUE TITLE
Text next to the fb like button on the top bar

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#106]
Do we want something witty there? I know if you ask 'please share' on twitter, shares go up by 60% or so. It's going to be very visible, so it might help us in the long run.

**Comment by jetlej** [comment]
Yeah might as well. So just... 'Like us!' ?

**Comment by MSchirp** [comment]
Hmmm, something more HE? Like, challenge yourself? transcend the bullshit? I think triggering the FOMO would be best.

**Comment by jetlej** [comment]
Well those don't really match up with liking us on Facebook. It needs to be obvios what we're asking them to do.

**Comment by lostboyevsky** [comment]
'Like us, humans!' -- obvious what we're saying, and "humans" adds an HE touch.

This reminds me: do we want to change the 'Like us on the Crackbook!' message on 6.0? I'm on the fence about "crackbook."

**Comment by jetlej** [comment]
After playing with this, I agree with Bates. It makes the header too busy. Not worth it.
