### ISSUE TITLE
Facebook // wordpress

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#107]
For some sites, if you link an article from them on fb, it automatically puts a direct link to your Facebook page. I this is great for conversions. See screenshot: 

![screen shot 2015-10-19 at 16 07 15](https://cloud.githubusercontent.com/assets/13124056/10580008/ad04f85e-767b-11e5-860b-ea329c19750d.png)

The guy from higher perspective said it was due:

You just add you Facebook profile in as the Facebook url in your WordPress account that publishes your articles.

When I asked if there was a specific place for that, he said: Yeah in the user section

**Comment by jetlej** [comment]
Btw this only links to Facebook user profiles, not to the website or to a fan page. So it's only good for the author. 

If you want this, you you can add your facebook profile URL by going to Users > My Profile 

![image](https://cloud.githubusercontent.com/assets/1179057/10607272/79a81fbe-7706-11e5-8dc0-edbad2fc0498.png)

**Comment by MSchirp** [comment]
It's not that. See the screenshot bottom right, it says 'by the cinematika'. Higher perspective also has this on their fb page, see for example: https://www.facebook.com/HigherPerspective/posts/1092419427457042

**Comment by MSchirp** [comment]
@jetlej

**Comment by jetlej** [comment]
Ah I see. Fixing that now.

**Comment by jetlej** [comment]
Ah I see. Fixing that now.
