### ISSUE TITLE
Leadpages pop up code for targeting specific urls

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#108]
Hey J, we recently learned that LeadPages' default pop up options do not: 

a) Allow a different pop up for those who are logged in vs. logged out
b) Allow certain pop ups to be used or excluded on specific URLS

To get around this problem Martijn proposed a solution:

In the backed you could create custom fields where we can paste our leadpages template links. 

1) A logged out pop up field. 
2) A logged in pop up field
3) In the edit section of every page and post a box where we can replace the leadpages link with an alternative OR disable leadpages.

Is this doable?

**Comment by jetlej** [comment]
@JonBrooksX - Before we do this, I suggest we find an alternative with the ability to at least target certain pages. That's basic functionality. LeadPages seems to be more about actual landing pages instead of popups anyways.

**Comment by MSchirp** [comment]
Unfortunately, we already got an annual subscription to leadpages yesterday before we found out about these shortcomings. They offer simple html codes to post on the actual blog posts, and based on my limited coding knowledge, having two boxes on all blog posts, one for logged in, one for logged out, that is auto populated with all our code and can be easily replaced on specific blog posts, would be an ideal solution for us to easily get this working.

**Comment by jetlej** [comment]
Get a refund. Then make sure it's the absolute best option before getting a year subscription.
