### ISSUE TITLE
Add Blinkist tracking pixels to daily, weekly, and monthly mail template

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#110]
These are the tracking pixels for the mail templates. I don't know how to add them. I think they just need to go in the HTML? 

Daily mail 

[open bracket] img src="http://jump.blinkist.com/aff_i?offer_id=2&aff_id=1715&source=dailymail" width="1" height="1" / [close bracket]

Weekly mail

[open bracket] img src="http://jump.blinkist.com/aff_i?offer_id=2&aff_id=1715&source=weeklymail" width="1" height="1" / [close bracket]

Montly mail

[open bracket] img src="http://jump.blinkist.com/aff_i?offer_id=2&aff_id=1715&source=monthlymail" width="1" height="1" / [close bracket]

**Comment by jetlej** [comment]
Added :)
