### ISSUE TITLE
Second white space contains wrong ad

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#111]
See screenshot:

![screen shot 2015-10-23 at 00 32 38](https://cloud.githubusercontent.com/assets/13124056/10680182/aba16d40-791d-11e5-90c6-6e2bfe435c59.png)

**Comment by jetlej** [comment]
@MSchirp - Change this in HE Options

**Comment by MSchirp** [comment]
Which one is it?

**Comment by jetlej** [comment]
@MSchirp - I answered this elsewhere, forget where. 'Homepage Mid-Article'.
