### ISSUE TITLE
Ajax loading ads

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#113]
See screenshot:

![screen shot 2015-10-23 at 00 41 19](https://cloud.githubusercontent.com/assets/13124056/10680318/e6138d90-791e-11e5-9936-bdf310cdcef7.png)

**Comment by jetlej** [comment]
I believe this is how it works right now. We can't load certain ad types via AJAX. Eg. Google ads.

**Comment by MSchirp** [comment]
oh wow, wish I had known that before I said yes to AJAX. Im estimating that that will cost us about 1-2k a month then. Not worth it, unfortunately.

**Comment by MSchirp** [comment]
Same goes for discussions :(

**Comment by jetlej** [comment]
I'll figure something out
