### ISSUE TITLE
Button or link needed on front page "quote section"

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#116]
![screenshot 2015-10-23 00 52 23](https://cloud.githubusercontent.com/assets/13107838/10681366/6b4733e4-7920-11e5-9682-c0a2b904a431.png)

Do you see "more topics" with the arrow. I think we need something like that but with "more quotes". I remember there being something like this at some point. Not sure why it isn't showing up here now.

**Comment by MSchirp** [comment]
Because the quotes page was bland and a dead end. We can add it back when we have a designer.

**Comment by JonBrooksX** [comment]
I see. Looks good as it is for now.
