### ISSUE TITLE
sometimes notifications button doesn't work properly

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#119]
this was an issue on 5.0 too, but i've forgotten to mention it. sometimes when i click the notifications button i get a drop-down showing notifications, and sometimes it takes me directly to another page to show me notifications. i think it should always show the drop-down first and only take me to another page if i click 'see all'

**Comment by MSchirp** [comment]
This is for our new coder, J mentioned before this a won'tfix issue.

**Comment by jetlej** [comment]
Fixed
