### ISSUE TITLE
quote formatting suggestion for front page

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#122]
right now we just have a hyphen before the author's name on the front page for quotes. can we change this to an em dash? -- i.e. one of these: — 

i think an em dash before the author's name looks more beautiful and sleek and seductive and sexy, but maybe i'm just a neurotic SOB

**Comment by JonBrooksX** [comment]
> i'm just a neurotic SOB

+1 

But still, good suggestion. We want this part of the site to be perfect.

**Comment by jetlej** [comment]
Done
