### ISSUE TITLE
'Store' button goes to shitty page that just says 'books'

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#124]
can we change 'store' page to some big message saying 'HE Store Coming Soon! :)'

**Comment by MSchirp** [comment]
+1

**Comment by jetlej** [comment]
@MSchirp , @lostboyevsky - You can remove or edit this link in Appearance > Menus

I'm not going to do it so you remember how to do this :)

**Comment by JonBrooksX** [comment]
Cool, @lostboyevsky can you implement this?

**Comment by MSchirp** [comment]
Done
