### ISSUE TITLE
signing in with Facebook

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#127]
this is a small thing, but i tested the feature that lets you sign in with FB and noticed that when it pulls up FB to ask for permission, it doesn't show our current logo. it shows a really old version of the HE logo. would be cool if it showed our current logo

**Comment by jetlej** [comment]
I replaced it with the 5.0 logo. @JonBrooksX - Where are the PSD's for the new logo with purple?

I will also go through and organize all of our graphics and PSD's to make sure we have easy access to all logos, etc.

**Comment by JonBrooksX** [comment]
![he fb profile pic all colors](https://cloud.githubusercontent.com/assets/13107838/10694689/7e937418-7997-11e5-8515-94849f21861e.jpg)
![he fb update](https://cloud.githubusercontent.com/assets/13107838/10694693/827814a8-7997-11e5-9c9a-584840732d7f.jpg)

I saved it as Jpg because I only changed the colors with bucket tool. 

Lemme know if there was something else you needed?

**Comment by dpatil-gmcs** [comment]
@jetlej @lostboyevsky :
Are you referring to the highlighted image in below screengrab?
![selection_086](https://cloud.githubusercontent.com/assets/5171153/12237234/b324274a-b8a3-11e5-9c92-f4883b39e00c.png)

**Comment by dpatil-gmcs** [comment]
@JonBrooksX @jetlej @lostboyevsky : 

If the above attached image is what we need to change, Do you think you could SET this image via the Facebook APP https://developers.facebook.com/apps/ you have created ? I think this image shows up from there. 

Please let me know  your comments on the same. Thanks !

**Comment by jetlej** [comment]
@dpatil-gmcs - I'll take care of this

**Comment by jetlej** [comment]
@JonBrooksX - I need a version of the logo that is 1024 x 1024

**Comment by JonBrooksX** [comment]
![highexistence-fb-logo](https://cloud.githubusercontent.com/assets/13107838/12360717/86b9ff34-bbb1-11e5-91db-1ca361352478.png)

@jetlej

**Comment by jetlej** [comment]
That looks fantastic ;) Switching this out now
