### ISSUE TITLE
upvoting comments or discussion replies does some weird shit

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#128]
try it. it shows you two blue hearts, one broken and one whole and says 'loved it!' ... looks sloppy, something definitely off here ... i think for upvotes it should just increase the count by 1 and not do anything else

**Comment by MSchirp** [comment]
![screen shot 2015-10-23 at 12 12 24](https://cloud.githubusercontent.com/assets/13124056/10690016/5852d8f6-797f-11e5-9f47-bfa5ce73db39.png)

**Comment by jetlej** [comment]
Fixed

**Comment by MSchirp** [comment]
@jetlej This is still happening.

**Comment by jetlej** [comment]
@MSchirp - Whoops, needed to clear cache :)
