### ISSUE TITLE
text is still wrapping around pictures in a shitty way on newest blog post

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#130]
look at the text next to the pics of team members on this post: http://www.highexistence.com/creative-destruction-a-farewell-letter-to-jordan-lejuwaan-and-a-message-to-all-hethens-regarding-the-future-of-highexistence/

jordan, your fix must not have worked or must have gotten removed somehow

**Comment by jetlej** [comment]
Slacked you about this
