### ISSUE TITLE
'recommended posts' sidebar widget not showing up for users who aren't signed in

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#131]
self-explanatory

**Comment by jetlej** [comment]
@lostboyevsky - On the single blog post page? I see it working.

**Comment by lostboyevsky** [comment]
yeah on single blog posts it wasn't for me the other night. I can try to fiddle with it again to see under what circumstances it didn't work.

**Comment by jetlej** [comment]
@lostboyevsky - Just re-open this issue if you figure it out
