### ISSUE TITLE
issue with discussion formatting

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#133]
i think there are actually multiple issues with discussion formatting. a couple ones i've noticed for now:

- different font styles are allowed. i think we should limit it to one font style, so that even when you paste in text, it is automatically converted to our default font. 

- when i click '12' on font size, it automatically selects '11' instead

- when one clicks 'edit' on a post, the line breaks get messed up. sometimes line breaks are eliminated, and sometimes line breaks seem to be doubled 

- not sure if this issue is still a thing, but on 5.0 there was always that issue where sometimes when you would edit a post, a bunch of HTML/CSS would show up in the post

**Comment by jetlej** [comment]
Now font styles are removed on paste, which also solves you're 4th issue. #2 and #3 can be fixed by someone else.

**Comment by MSchirp** [comment]
They are still allowed tho, see screenshot, @jetlej :+1: 

![screen shot 2015-10-25 at 00 35 54](https://cloud.githubusercontent.com/assets/13124056/10713105/5fcb9a1e-7ab0-11e5-9621-1bdff9603fb5.png)

**Comment by jetlej** [comment]
@MSchirp - Can you link me to that discussion?

**Comment by lostboyevsky** [comment]
it's here: http://www.highexistence.com/topic/question-of-the-day-soulmates/

interestingly, i was just coming on here to link to the exact discussion, then saw martijn's screenshot.

**Comment by jetlej** [comment]
Found a bug that was breaking the removal of HTML on pasting. Verified fixed!
