### ISSUE TITLE
'Pin' and 'Promote to Front' aren't doing anything for discussions

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#134]
i've added a new discussion to HE and clicked both of these buttons, and the discussion is not showing up on the front page

**Comment by jetlej** [comment]
@lostboyevsky - Use 'Pin' for choosing the discussion that shows above the fold, 'Front' for discussions showing in that gray sidebar on the homepage. 'Front' should be fixed now.
