### ISSUE TITLE
front page advertising confusing on the backend

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#136]
There are no distinct categories for advertising for the frontpage in the backend. It seems to be automatically picking the google ads, but preferably, we want to customise each and every one.

See screenshots:

![screen shot 2015-10-23 at 15 50 05](https://cloud.githubusercontent.com/assets/13124056/10694391/33b77550-799e-11e5-8117-63cb3a82870f.png)
![screen shot 2015-10-23 at 15 49 59](https://cloud.githubusercontent.com/assets/13124056/10694392/33d4945a-799e-11e5-9788-38b0e0792b87.png)
![screen shot 2015-10-23 at 15 49 31](https://cloud.githubusercontent.com/assets/13124056/10694394/33d74b1e-799e-11e5-968d-4147544a2bc3.png)
![screen shot 2015-10-23 at 15 50 13](https://cloud.githubusercontent.com/assets/13124056/10694393/33d68c4c-799e-11e5-864a-c93b906d79b4.png)

**Comment by jetlej** [comment]
@MSchirp - It's pulling from Homepage Mid Listing, which I think sounds pretty straight-forward

**Comment by MSchirp** [comment]
Ah, that makes sense @jetlej . I thought that was an old one because the tags that it contained were from tribalfushion but it was showing google ads instead (and two different sizes too.)

Still, we don't want all of them to be the same all the time. Especially when we have our own products out.

And the third one and lower don't show up at all.
