### ISSUE TITLE
Spacing could be improved on homepage QOD

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#138]
I think from a design perspective it would look better is the image was aligne with the adjacent headings rather than "question of the day" text. See the ungainly white space above the text? 

![screenshot 2015-10-23 15 08 40](https://cloud.githubusercontent.com/assets/13107838/10696421/99b44814-799f-11e5-9b8c-4474c8ef997f.png)

**Comment by jetlej** [comment]
@JonBrooksX - You can just delete the title in HE Options
