### ISSUE TITLE
Discussion page 'top posts week + month' algorithm not working correctly

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#139]
A new discussion is on top of both?

![screen shot 2015-10-23 at 17 06 56](https://cloud.githubusercontent.com/assets/13124056/10696503/9f569d9a-79a8-11e5-889a-f7152789922b.png)

**Comment by jetlej** [comment]
I'm stumped on this one, so I just posted in StackOverflow: http://wordpress.stackexchange.com/questions/206441/ordering-topics-by-most-replies-in-x-days-using-mysql-statement

**Comment by jetlej** [comment]
Fixed
