### ISSUE TITLE
seems to be an issue with the 'recommended posts' sidebar

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#140]
can't quite place what it is, but it's like the sidebar is freezing so that you can't scroll down the list sometimes

**Comment by jetlej** [comment]
@lostboyevsky - What sidebar are you talking about? None of them say 'recommended posts'

**Comment by lostboyevsky** [comment]
sorry, the right sidebar that shows up on blog posts and recommends other blog posts.
