### ISSUE TITLE
Advertising goes black sometimes and suddenly, keeps reloading and immediately going black again

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#142]
For example, on the left here: http://www.highexistence.com/topic/what-is-the-greatest-impact-highexistence-has-had-on-your-life/

See screenshot:

![screen shot 2015-10-25 at 00 15 25](https://cloud.githubusercontent.com/assets/13124056/10713039/e184d1c2-7aad-11e5-8223-2be9e473344b.png)

**Comment by jetlej** [comment]
This is Sekindo's issue. An ad is an iframe that is totally inaccessible to me even if I wanted to screw with it (purposefully).
