### ISSUE TITLE
"Blog page" has the same posts repeated over and over

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#143]
See: http://www.highexistence.com/blog/

**Comment by MSchirp** [comment]
![screen shot 2015-10-25 at 22 20 56](https://cloud.githubusercontent.com/assets/13124056/10717942/be1bd12c-7b66-11e5-9ae7-35bb367dd848.png)

**Comment by jetlej** [comment]
Confirmed fixed now :)
