### ISSUE TITLE
Articles jitter about when scrolling on iPhone and iPad

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#145]
Check Slack #codebugs for video.

**Comment by jetlej** [comment]
Oo. That is not good. I really don't know what could be causing that. Sure your iPad is okay? haha. 

Is it only on certain pages? Please give as much detail as possible.

**Comment by JonBrooksX** [comment]
It's the same on iPhone for me. Perhaps you could try opening an article on you iPhone and scrolling down so that I know it's not just my interenet connection (it's been slow last few weeks).

**Comment by jetlej** [comment]
I can't replicate this on my iPhone. @lostboyevsky, @MSchirp, can you guys try on your iDevices?

**Comment by MSchirp** [comment]
This only happens when I scroll really quickly, so not really worth going into imo. (This was also the case for you right, @JonBrooksX ?)

**Comment by JonBrooksX** [comment]
No it's happening when I scroll slowly too. It jitters. There are also
black areas that keep appearing. I've got much faster internet now and it's
still happening. Not sure what's going on. If everyone is experiencing this
on mobile it's not good. Definitely think we should all do some testing to
find out what's going on here. Just open an article on your iphone and
explore the article a little and see what happens.

**Comment by MSchirp** [comment]
Just did this to double check, nothing happens (well, the top bar is a little jittery, maybe.) @lostboyevsky Could you give this a shot?

**Comment by lostboyevsky** [comment]
i'm not seeing any jittering on my iPhone. the only thing i see is that i can move the screen horizontally and see some charcoal-colored areas to the left and right of the screen if i want to. most top sites seem to have it frozen in place so that you cannot do this. but on pure vertical scrolling i am not seeing any jittering.

**Comment by jetlej** [comment]
I'm thinking this may have been caused by the ajax loading. @JonBrooksX - Can you check again?

**Comment by JonBrooksX** [comment]
Wow, it’s working perfectly now. :)

— no jitters.
