### ISSUE TITLE
password reset issue

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#146]
This user mailed us, I have reset his pass manually already. 

'
undefined: e2c15d5ffb

undefined: /contact/

Name: BoleroBlue

Email: ldccruz@hotmail.com
Subject: Password reset and login issue

Message:
I have trouble signing in with my password so I decided to reset it. But then I have trouble resetting my password as it won\'t let me. It sends me a link in my email and I click it the moment it comes but it tells me the link has expired at least 6 times over! Might this be a technical problem? Thanks

**Comment by jetlej** [comment]
Upgrade the plugin and now it works
