### ISSUE TITLE
Can't respond to comments on blog post anymore

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#147]
In the non-ajax version, clicking reply to a comment just refreshes the page. 

See for example: http://www.highexistence.com/creative-destruction-a-farewell-letter-to-jordan-lejuwaan-and-a-message-to-all-hethens-regarding-the-future-of-highexistence/

In ajax version, you can reply, but when you post, it gives an error. (But the reply is still posted anyways.)

**Comment by MSchirp** [comment]
![screen shot 2015-10-26 at 15 42 08](https://cloud.githubusercontent.com/assets/13124056/10731989/3ccb77b6-7bf8-11e5-8b62-034cf0b91fe8.png)

**Comment by jetlej** [comment]
@MSchirp - I can't replicate this on ajax or non-ajax. Can you try again? Sometimes it just bugs out.
