### ISSUE TITLE
Ad switcher for homepage ads

### ISSUE THREAD

**Issue by jetlej** [jetlej/HE-6.0-Bugs#148]

**Comment by MSchirp** [comment]
What is this? If I am reading this right, we can just use adbutler for this? :)

**Comment by jetlej** [comment]
We can, but only if I figure out how to ajax-load their scripts. Actually that's a great test. Would you mind inputting some homepage ads in Adbutler and using their script so I can do some testing? @MSchirp

**Comment by MSchirp** [comment]
I wouldn't mind at all if I had a better idea of what you are asking. @jetlej 

You want to ajax-load ad butler ads. You want me to set up 'homepage ads' in adbutler? And then use the script how? And you will test this where?

**Comment by MSchirp** [comment]
Let me know so I can get this done. @jetlej
