### ISSUE TITLE
Confusion between front page, stick, unstick and pin

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#150]
These terms seem to be issued intermittently on the discussion page, inside the actual discussion and editing the discussion in the backend. You also get different notifications depending on what you use. 

Also, to front is also different it seems.

See screenshots:

![screen shot 2015-10-26 at 16 17 41](https://cloud.githubusercontent.com/assets/13124056/10733137/abb55dfe-7bfd-11e5-8b0a-81dd7acf144c.png)

Would be helpful if we could use the same description on all places. 

![screen shot 2015-10-26 at 16 23 53](https://cloud.githubusercontent.com/assets/13124056/10733199/fbf53e42-7bfd-11e5-8a91-063625b23d4b.png)

Also, the QOD doesn't have any options at the discussion page to put it to the front?

**Comment by jetlej** [comment]
Those links on the topic pages are old BBpress tools that don't work anymore. I'll remove them and will replace them with the real ones.
