### ISSUE TITLE
Uploading image to body of discussions--met with blank page

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#151]
This is the second time it's happened to me. 

This is the link. I can't see it. 

http://www.highexistence.com/topic/question-of-the-week-regrets/

![screenshot 2015-10-26 16 02 32](https://cloud.githubusercontent.com/assets/13107838/10735931/50fadb14-7c02-11e5-8944-a42e52ab034b.png)

**Comment by jetlej** [comment]
Hmm it works fine for me. Ajax and non-ajax. Can @MSchirp or @lostboyevsky replicate this?

**Comment by jetlej** [comment]
How were you even doing this? I had image inclusion disabled on topics for some reason. Now it's enabled. 

Please test again.

**Comment by JonBrooksX** [comment]
I was just dragging the image in from finder. Okay, will test again.

**Comment by jetlej** [comment]
@JonBrooksX - Did you test again?

**Comment by JonBrooksX** [comment]
Yeah, works perfectly!
