### ISSUE TITLE
weekly + monthly mail system not working properly

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#152]
In the weekly options, no articles show up. Just 'none'. See screenshot.

In the monthly option, there seems to be a max of 5 articles. This needs to be increased to 10. See screenshot.

![screen shot 2015-10-27 at 12 34 35](https://cloud.githubusercontent.com/assets/13124056/10756916/66e967ce-7ca7-11e5-80fc-fdd28165f95b.png)
![screen shot 2015-10-27 at 12 34 27](https://cloud.githubusercontent.com/assets/13124056/10756917/6706ad34-7ca7-11e5-9f38-d10a5d43139c.png)

**Comment by jetlej** [comment]
No this looks right. Weekly pulls posts from the last 7 days. At the time, nothing had been published since the farewell article which was just over 7 days before. 

Same for month. It pulls posts from the last 30 days.

**Comment by MSchirp** [comment]
It would be infinitely better if it would just pull the latest 10. It rarely happens that the 7 day period limit (or the 30 day for month) matches the input we want to send out. @jetlej
