### ISSUE TITLE
Shockwave plug in stops reacting / goes to overdrive

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#154]
When I visit HE on safari, flash goes into overdrive. I have heard from others that the shockwave plug in keeps crashing.

**Comment by jetlej** [comment]
I think this is from the video ads. I noticed they are sending out TONS of requests every second. Nothing else on our website uses flash besides maybe Youtube, which is not the problem.

**Comment by MSchirp** [comment]
It is curious that it only started happening after 6.0, no? Perhaps it has something to do with: https://github.com/jetlej/HE-6.0-Bugs/issues/142 ?

**Comment by MSchirp** [comment]
Just to be sure, I removed them from the frontpage and added google skyscraper ads there.

**Comment by jetlej** [comment]
@MSchirp - Did that solve it? I can't replicate on Safari. Which pages caused it to freak out? Was it after a lot of infinite scroll? More details please.

**Comment by jetlej** [comment]
I think this may be related to #145. I suspect shitty ads from Sekindo zapping memory and crashing flash.

**Comment by MSchirp** [comment]
Haven't seen it since. Will notify you when I do.
