### ISSUE TITLE
when one clicks 'edit' on a discussion post, it takes you to a totally new page

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#155]
i don't think it did this before? would be great if it just allowed you to edit your comment on the page that your'e on. 

also, not only does it take you to a totally new page, but it removes the line breaks from whatever you had typed, creating just one big wall of text. you have to go back through and reapply your line breaks or else they're lost. we should change this.

**Comment by jetlej** [comment]
It always brought you to a new page. Only comments can be edited inline.

Doesn't it bring you to wp-admin when you click edit? It should do that for admins. 

I just fixed the line-break issue. Pleas verify.
