### ISSUE TITLE
new quotes added show up on homepage

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#157]
quotes don't look good on the homepage, but i need to add new ones to keep updating the quote section on the homepage.

one way around this would be to just continuously edit the same quote to make it a new one, but then we lose value by not having all of these great quotes in our database. is there an easy way to make it so [post type: quote] does not appear on the homepage? i fear there is not, as i know you said this would be difficult to do for videos and images, jordan.

**Comment by jetlej** [comment]
Removing quotes from frontpage completely
