### ISSUE TITLE
blog posts not displaying on homepage below the fold

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#159]
i noticed i'm not seeing our blog posts interspersed in with the rest of the content in the infinite scroll on the homepage. i saw some of them the other day, but now they're gone. wondering what's up. 

also, idea: once blog posts are showing on the homepage again, there might be a simple way to get 15-20 of them at the top of the homepage: we can simply change the published date on all of them in the backend to sometime within the last week.

**Comment by MSchirp** [comment]
Great suggestion!

**Comment by jetlej** [comment]
My bad. Fixed
