### ISSUE TITLE
found a blog post in which the URL changes as you scroll through it

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#161]
URL changes at least twice for me as i scroll through the body of this article: http://www.highexistence.com/100-science-fiction-books/

see if this is happening for you

**Comment by jetlej** [comment]
Yeah it changes as the next article in infinite scroll loads. Expected behavior. 

Are you seeing something different? @lostboyevsky

**Comment by jetlej** [comment]
The purpose is that you can copy/paste the link when the page switches to the next article
