### ISSUE TITLE
Could we show number of comments at the top of the discussion?

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#163]
![screenshot 2015-10-30 22 38 12](https://cloud.githubusercontent.com/assets/13107838/10859710/01c41c50-7f58-11e5-804c-84a74532b9b8.png)

This discussion is getting many comments. Would be cool if we could see total number of comments at the top. Especially for those who click onto the discussion, as I did, from their notifications.

**Comment by jetlej** [comment]
The answer is NO @lostboyevsky. VR porn is going to be fantastic, and I guarantee you will try it and like it once the technology is there ;)

But yes we should add # of comments to the top.

**Comment by lostboyevsky** [comment]
the tech is already there, @jetlej, or so i've heard. supposedly PornHub already has a VIP section for VR porn. 

my question was whether *you* (addressing all HEthens) are unsettled by the developments, so there isn't a single 'yes' or 'no' answer to this question. subjectively, i am unsettled by it. i don't doubt that it could be awesome, and maybe i will try it someday, but i still feel weird about it.

**Comment by MSchirp** [comment]
@jetlej I assigned @dpatil-gmcs to this one. Please confirm this is ok.

**Comment by dpatil-gmcs** [comment]
@MSchirp : 
Awaiting @jetlej sign off for this task. 
Our understanding for the task is clear : "Basically we want to display a Comment Count for any given Post"

Questions : 
1. Comment Count should be visible for Anonymous users as well ? This query since anonymous users cannot post a comment.

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej :
This issue is implemented locally but for only logged in users.  Let me know if this comment count should be visible for anonymous users as well ?
Thanks..!!!

**Comment by MSchirp** [comment]
@dpatil-gmcs Yes, this should be visible to anonymous users as well!

**Comment by MSchirp** [comment]
Ill just add this here, discussions should always be visible for non-logged in users too. This page, however, is not completely visible: http://highexistence.com/topic/can-a-relationship-work-if-one-partner-is-highly-religious/ (comments and left sidebar)

**Comment by dpatil-gmcs** [comment]
@MSchirp :
Code has been checked in to PROD Branch with Commit # : 0b82de93
Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by dpatil-gmcs** [comment]
Task effort:
Task Understanding: 15 Minutes
Finding out the place: 30 Minutes
Implementing: 30 Minutes
Testing: 30 Minutes

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE
