### ISSUE TITLE
Add some HTML to "Blog related post ad #2"

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#165]
I don't know how to do this or if I can. I want to track the impressions on the blinkist ad in "blog related post ad #2". 

This is the tracking code: 

[open bracket] img src="http://jump.blinkist.com/aff_i?offer_id=2&aff_id=1715&source=belowpost_recommendwidget" width="1" height="1" / [close bracket]

Could you add it or show me how? Thanks!

**Comment by jetlej** [comment]
I just added an option to include tracking codes in the 'Blog related post ad' options. I'll fill this one in for you as a freebie :)
