### ISSUE TITLE
Image overriding top navigation bar in articles

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#166]
See screenshot:

![screen shot 2015-11-03 at 11 43 31](https://cloud.githubusercontent.com/assets/13124056/10907118/b0dd9d0c-8227-11e5-9c3b-0b1b8e4db9a1.png)

**Comment by jetlej** [comment]
I just put some shitty CSS into the actual blog post way back when. Fixing now
