### ISSUE TITLE
Front page 'Discussion', 'Quote' and 'Ad/QOW etc.' are not aligned

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#167]
The third 'block' seems to be moved down in relation to the other two, see screenshot:

![highexistence_home_page__draft_design_filip_4_1024](https://cloud.githubusercontent.com/assets/13124056/10907177/23314db8-8228-11e5-86c8-f7b7dd780c37.png)

**Comment by jetlej** [comment]
Fixed
