### ISSUE TITLE
Missing 'short bio' on the front page?

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#168]
Do you guys feel we should have a short bio here too, the same on as discussions?

@JonBrooksX @lostboyevsky 

See screenshot, on the right of Steve Taylor:

![screen shot 2015-11-03 at 12 44 20](https://cloud.githubusercontent.com/assets/13124056/10907245/c0d3c488-8228-11e5-9e77-38b55c4ad6a9.png)

**Comment by jetlej** [comment]
Yes, easy add

**Comment by JonBrooksX** [comment]
Yeah, that'd be nice.

**Comment by jetlej** [comment]
Added
