### ISSUE TITLE
Frontpage uses social media images vs. header images

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#169]
See screenshots:

Backend:

![screen shot 2015-11-04 at 17 00 42](https://cloud.githubusercontent.com/assets/13124056/10943847/96a92394-8316-11e5-8228-69214d78e459.png)

Homepage:

![screen shot 2015-11-04 at 17 06 52](https://cloud.githubusercontent.com/assets/13124056/10943858/a019e80a-8316-11e5-9d0f-a64de3db608f.png)

**Comment by jetlej** [comment]
@MSchirp, @JonBrooksX requested this functionality

**Comment by JonBrooksX** [comment]
Well, one of the reasons that doesn't look so good is because the word "mindfulness" is cut off. Also, on HE 5.0 the title wasn't overlaid on the image. 

Could we perhpas remove this function from just above the fold?

**Comment by MSchirp** [comment]
Good solution Jon!

**Comment by jetlej** [comment]
Done
