### ISSUE TITLE
Threading in blog posts suddenly messed up

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#17]
In this post, MAGIC LOGICIAN and myself answered steve taylor directly. Our comments showed under his reply when I first posted. Now they are at the bottom of all comments.

**Comment by jetlej** [comment]
@MSchirp - What post?

**Comment by MSchirp** [comment]
this one: http://www.highexistence.com/mystical-science-a-voyage-beyond-the-limits-of-science/ <http://www.highexistence.com/mystical-science-a-voyage-beyond-the-limits-of-science/>

**Comment by jetlej** [comment]
Are you saying you both replied to HIS reply to Daniel Tate?

I just replied to that one and it's working as expected

**Comment by MSchirp** [comment]
Yes, we both did. And it showed up fine. But as more comments got in, they suddenly went down to the bottom.
