### ISSUE TITLE
Avatar not showing in e-mails

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#170]
See screenshot:

![screen shot 2015-11-06 at 16 11 57](https://cloud.githubusercontent.com/assets/13124056/11000305/35fbece8-84a1-11e5-93d4-1b2bfd3f7ace.png)

**Comment by MSchirp** [comment]
Hmm. it seems to be just Jon. Could you try and reupload your avatar to HE Jon? Perhaps that will fix it. @JonBrooksX

**Comment by JonBrooksX** [comment]
It's working now: 

![screenshot 2015-11-12 17 01 08](https://cloud.githubusercontent.com/assets/13107838/11124877/0c622e16-895f-11e5-9769-1f50485e9721.png)
