### ISSUE TITLE
Posts above the fold are also showing below the fold.

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#171]
If you look at the homepage, you'll see that the post that are in the featured area are also repeated beneath the featured area.

**Comment by MSchirp** [comment]
Im not seeing this, screenshot? @JonBrooksX

**Comment by JonBrooksX** [comment]
That's weird. It's not there now. Seems fine.

**Comment by MSchirp** [comment]
Hmm, I remember this happening before after I changed a few dates of blog posts. Seems to have happened again after I changed one again (to be able to be included in the daily mail.)

**Comment by JonBrooksX** [comment]
I think we can close this now because there is no sign of it now.
