### ISSUE TITLE
Change "Their website" to "learn more" in recommended product widget

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#172]
I know you're not taking on any more enhancements, but I feel like this would be really easy and quick to change and could help us earn more. This spot gets a ton of sales.

On the below the post widget we used to have two buttons, one with "their website" and the other with "read our review" but since we've deleted "read our review" we should change "their website" to something more appealing. I was thinking "learn more >".

EDIT: the image url doesn't point towards blinkist for some reason. This is where the image should lead when fixed: http://jump.blinkist.com/aff_c?offer_id=2&aff_id=1715&source=belowpost_ad

Also, perfect place to introduce the reddish orange color? 

![screenshot 2015-11-10 20 57 12](https://cloud.githubusercontent.com/assets/13107838/11075622/0b182d98-87ee-11e5-98d1-f42bff10d7bb.png)

**Comment by MSchirp** [comment]
Would come very handy to learn where we can edit it ourselves actually.

**Comment by MSchirp** [comment]
@jetlej Just checked, and we will need to change this ourselves for the aya ads too.

**Comment by jetlej** [comment]
@JonBrooksX @MSchirp - I added another field to the products for 'Button CTA Text' so you can change this yourself. It defaults to 'Learn More'.

**Comment by MSchirp** [comment]
awesome, thanks!
