### ISSUE TITLE
white space between google horizontal skyscraper ad and bio

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#174]
See screenshot:

![screen shot 2015-11-16 at 13 02 25](https://cloud.githubusercontent.com/assets/13124056/11181456/79d6a2b4-8c62-11e5-9b19-a6f9ad15058c.png)

**Comment by jetlej** [comment]
@MSchirp - The ad you setup has a size of 500x280, which is much larger than a leaderboard, which is (I think) 720x90
