### ISSUE TITLE
social media sharing widget appears incorrectly on safari on PC 

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#175]
![screen shot 2015-11-20 at 4 49 34 pm](https://cloud.githubusercontent.com/assets/9164601/11314360/8f85b56e-8faa-11e5-9c5c-02b967c71081.png)
on chrome, our social media sharing widget shows up along the left side of the post and stays there as one scrolls down. on safari, it only shows at the top and doesn't remain visible as one scrolls down. this could be an important fix:

**Comment by jetlej** [comment]
This is dependent on screen size, and is by design. I'm guessing you were working on a smaller screen where there is not enough space for the widget to be on the left side. 

I also just confirmed that it works fine in Safari.
