### ISSUE TITLE
recommendation widget sidebar sometimes showing duplicates

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#176]
![screen shot 2015-11-20 at 5 00 34 pm](https://cloud.githubusercontent.com/assets/9164601/11314380/af883436-8faa-11e5-9d23-9bf4dd370b7e.png)

**Comment by jetlej** [comment]
Just emailed them to ask about this

**Comment by jetlej** [comment]
This was fixed
