### ISSUE TITLE
iPhone issues: black screen

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#178]
![img_0692](https://cloud.githubusercontent.com/assets/13107838/11320353/06a3f8b6-908e-11e5-8c68-d212520ad83e.PNG)

On iPhone this black screen appears whenever you scroll either side.

**Comment by jetlej** [comment]
@MSchirp - This is because the leaderboard ad code at the bottom of blog posts is not responsive. It should auto-switch to 300x250 or smaller on mobile devices.
