### ISSUE TITLE
iPhone issue: no comment box

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#179]
I don't see a comment form OR comments on my iPhone when I click an article from the front page. 

![img_0693](https://cloud.githubusercontent.com/assets/13107838/11320358/34487346-908e-11e5-96b2-0cb42386d763.PNG)

**Comment by jetlej** [comment]
I see it. Can @MSchirp and @lostboyevsky confirm?

**Comment by MSchirp** [comment]
I see it too.

**Comment by JonBrooksX** [comment]
What phone is everyone using? I'm using iPhone 6+, safari.

**Comment by lostboyevsky** [comment]
i can see comments just fine on both my Google app (not Chrome, just the search app) and Safari. i'm on an iPhone 5.

**Comment by jetlej** [comment]
I can see on iPhone 5s, Safari and Chrome
