### ISSUE TITLE
The basic email template has a wrong link hardcoded in it

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#182]
One comes up when you use a H1 title, it links to hethens.com. See screenshot:

![screen shot 2015-11-26 at 18 11 43](https://cloud.githubusercontent.com/assets/13124056/11428210/3e27266c-9469-11e5-8ee4-ea826dfcda6c.png)

And:

![screen shot 2015-11-26 at 18 13 15](https://cloud.githubusercontent.com/assets/13124056/11428229/772ce03c-9469-11e5-821b-09a5343d7b67.png)
(See bottom left)

The other one comes up when you add an image, it also leads to the there is no spoon image on hethens.com.

![screen shot 2015-11-26 at 18 14 55](https://cloud.githubusercontent.com/assets/13124056/11428239/a4781746-9469-11e5-947d-9a33e437e749.png)

---------

I can overrule the image one but not the title one.

**Comment by jetlej** [comment]
Fixed
