### ISSUE TITLE
Sajari update

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#184]
See screenshot of our convo in Slack :)

![screen shot 2015-11-27 at 18 56 01](https://cloud.githubusercontent.com/assets/13124056/11446543/a5277414-9538-11e5-8cc0-f61f2b9504ed.png)

**Comment by jetlej** [comment]
I fixed the duplicate issue and increase the number to 10. I'll leave the combining of the 3 types of algorithms to the new developer.

**Comment by jetlej** [comment]
NOTE: Sajari is used in 3 different places, so this needs to be fixed for all 3.

**Comment by dpatil-gmcs** [comment]
@jetlej @MSchirp : 

Let me frame our understanding on Sajari :

10 Recommended articles should be displayed in following way.

1-3 must be BEST match
4-7 must be POPULAR
8-10 must be RECENT

Currently we have configured only for 10 'related' articles. We have to configure it for 'best', 'popular', 'recent'.
And to do so we have to call API 3 times and merge the results.

Assumptions : 

1. In case, we don't receive ANY Posts for the "Best Match" API Call, our recommended Posts will start listing the Popular matches followed by Recent Posts.

2. We are assuming that we will be displaying 10 Posts at any given point in time (after removing duplicates)

Kindly let us know your thoughts on the same. Thanks !

NOTE : We have already started identifying those important pieces of code required for our implementation.

**Comment by jetlej** [comment]
@dpatil-gmcs - Our thoughts are the same. Please go ahead with this!

**Comment by dpatil-gmcs** [comment]
@jetlej @MSchirp :
Code has been checked in to PROD Branch with Commit # : 9c282b85
Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by MSchirp** [comment]
@jetlej How can I check if this is working properly? The test site doesn't run Sajari as far as I can tell.

**Comment by dpatil-gmcs** [comment]
@jetlej : Yes I agree with @MSchirp . The Sajari API FAILS and give an HTTP 401 meaning URL resource requires user authentication...I think the Staging Site domain is NOT authorized with Sajari. Hence the BLANK UI.

**Comment by jetlej** [comment]
Okay I am submitting a support request to Sajari to ask about this.

**Comment by dpatil-gmcs** [comment]
@jetlej : 
Just a suggestion : 
If you have Sajari Account details may be there is a provision to register the Staging DOMAIN Name so that Sajari could serve for the Staging domain as well.

**Comment by jetlej** [comment]
Sorry I forgot to submit the support request! I'm doing that now. @dpatil-gmcs

**Comment by mish15** [comment]
You need to add domains you wish to authorize in the admin section of the console by:
a) Select your collection
b) Click "setup"
c) Click "edit"
d) Add the domain and it will then authorise straight away.

Note: *if* your staging site is publicly available and you add the base install code to it, Sajari will see it as legitimate content and try to index it. You can avoid this in one of two ways:
a) Add a "ranking rule" to omit all pages from this domain. Or
b) Add "data-sj-noindex" to any element on these pages and they won't be indexed. See https://www.sajari.com/site-crawling for more info on indexing options.

**Comment by dpatil-gmcs** [comment]
@jetlej : As we rightly assumed what @mish15 mentioned, I think you will have to take up this one at your end.

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE
