### ISSUE TITLE
I'd like to be able to edit previous discussions

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#185]
I just tried to edit a previous discussion to make it more clickable from the google search results but I had the message "you are not allowed to edit posts as this user."

Could you change my permissions so that I can do this?

@MSchirp @jetlej

**Comment by jetlej** [comment]
@JonBrooksX - Me changing you to a Keymaster most likely fixed this. If not, edit it through wp-admin instead
