### ISSUE TITLE
A top voted/loved of all time page, preferably able to sort on category

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#187]
just an enhancement for the new coder

**Comment by MSchirp** [comment]
To clarify, on this page: http://highexistence.com/blog/ just above the blog posts, we would like a way to filter our own blog posts with the following variables:

Most Loved / Least Loved (popularity filter)
Time period (date filter)
Category (category filter)

**Comment by MSchirp** [comment]
Any suggestions @lostboyevsky @JonBrooksX ?

**Comment by lostboyevsky** [comment]
i like those filters. i think we should use the same filters we had in HE 5.0 -- can't remember specifically what all of them were, but they worked well

**Comment by dpatil-gmcs** [comment]
@MSchirp :
1. How are we planning to interpret the Most Loved / Least Loved (popularity filter) ?
2. Do we want to use the plugin : Demo URL : http://demo.designsandcode.com/sfpro-movie-reviews/
OR Do we want to use a SIMPLISTIC approach which is implemented from Scratch which would have a Dropdown for Popularity / Date / Category
Assuming Category is selected then a DROP down listing ALL related Categories will be visible and clicking APPLY would populate relevent Posts.

Please let us know your comments around our suggestion, that way we can estimate. Thanks !

**Comment by dpatil-gmcs** [comment]
@MSchirp :
Please let us know your comments on our suggestion.
Thanks ..!!

**Comment by MSchirp** [comment]
@dpatil-gmcs I think a simplistic approach would work best! Not sure if I understand your point 1. ? Users can now 'love' a post. We have a database with articles that have been loved the most. I want to give users the capability to sort by loved (most loved vs. least loved), in a certain time span (see screenshot), per category.

![screen shot 2016-01-19 at 17 29 00](https://cloud.githubusercontent.com/assets/13124056/12424878/7a8a5b90-bed2-11e5-8f5f-46123b0c9f47.png)

**Comment by dpatil-gmcs** [comment]
@MSchirp  Do you want this feature to be implemented on images and videos page as well or you want it only for the blog page?

**Comment by MSchirp** [comment]
On blog, image and video pages, thanks!

**Comment by dpatil-gmcs** [comment]
@MSchirp 
What remains is Synchronising blog auto scroll, with our filter criteria. Below mentioned is the current status : 

We have implemented the task, on local and I am attaching the screenshots of it, with the comment. Please have a look and let me know if you want any change in the functionality, or if you want to add something into it.
![initial_page](https://cloud.githubusercontent.com/assets/5171153/13319938/48c6c770-dbeb-11e5-9ace-86d324f53860.png)
Here none, of the above filters, is mandatory. Meaning, User can choose any filters user wishes.
![popular](https://cloud.githubusercontent.com/assets/5171153/13319972/743a21fe-dbeb-11e5-8738-da4c031c2a32.png)
![category](https://cloud.githubusercontent.com/assets/5171153/13319978/81778afa-dbeb-11e5-9882-f80a8c07d0e1.png)
![withenddate](https://cloud.githubusercontent.com/assets/5171153/13319980/88b85722-dbeb-11e5-8e63-a6f9af27017a.png)
The End date control will be visible only after user enters Start date, else it won't be visible.
![date_control](https://cloud.githubusercontent.com/assets/5171153/13319998/b032ca3a-dbeb-11e5-9076-a771efeecf50.png)
On clicking the filter button,the filtered list is updated on the page via AJAX, so that the page is not reloaded and the user gets better experience.

Please let us know your views on it!

**Comment by dpatil-gmcs** [comment]
@MSchirp 
Just an FYI, we are removing the jQuery infinite scroll and replacing it with the internally implemented autoscroll.
Reason being as we said earlier we might need to change the  jQuery plugin code and also synchronising jQuery infinite scroll with our filter can make it more complicated.

**Comment by dpatil-gmcs** [comment]
@MSchirp  We are done with the auto scroll implementation as well, for the blog front page, With this the ad related issue on the blog front page #250 will also be addressed. Please guve us the confirmation on the UI looking at the above screenshots, that way we can deploy it on staging.

**Comment by MSchirp** [comment]
Looks good, please put it up on TEST and I will let you know if its ready for LIVE.

**Comment by lostboyevsky** [comment]
Looks solid to me. It would be cool eventually for people also to be able to view 'Most Shared' and 'HE Team Favorites' or other things like that, but this is a good start that enhances the experience a lot

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @MSchirp  This issue is commited to the test site, and you will be able to see the changes as soon as the test site is up.

**Comment by MSchirp** [comment]
Noted

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp  Now that the TEST site is up, please have a look at the implementation and let us know your views on it so that we can deploy it on LIVE site.

**Comment by MSchirp** [comment]
Looks good!

Here are a few more changes:

Note, I am using this page:

- The top navigation bar is cut off on top.
- All the texts should be removed.  'Filter by', Popularity, Category and Start date.
- In popularity the text --select an option-- should be removed.
- It should be categorised using these categories: http://www.highexistence.com/wp-admin/edit-tags.php?taxonomy=category
- The date setting doesn't work. I expect it to open when you click on the option. 
- The css is different for the date setting than for the other options.
- I want one option with the date, and which then opens a box as I tried to show in my screenshot. That box has begin and end date. You can click these to set your time range. It also has the following options, see screenshot:

![screen shot 2016-03-04 at 17 35 11](https://cloud.githubusercontent.com/assets/13124056/13533192/ac379d80-e22f-11e5-80b5-6e5b45ae8349.png)

**Comment by dpatil-gmcs** [comment]
@MSchirp  I Understand your requirement, Technically it is feasible however, from the end user prespective I don't think it makes sense.
Resons Being:
Having two controlls for dates, 
1. Dropdown and
2. Jquery Calender controll is misleading to the User.

My Recommendation would be to show the date drop down with logical values. e.g : "Last 7 days", "Today" etc.
Please let me know your thoughts.

**Comment by MSchirp** [comment]
Fair enough. Use these logical value:

- Last 7 Days
- Last Month
- Last 3 Months
- Last 6 Months
- Last Year
- Last 2 Years
- Last 3 Years
- All Time

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have implemented the changes, and committed the code to the TEST site. Please have a look and let us know your views on it.
Note: All the logical values for Date Range, are considered from the current date.
e.g Last 7 days will show POSTS from 2nd March 2016 to 9th March 2016

**Comment by MSchirp** [comment]
This looks great @dpatil-gmcs, please push to live!

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have pushed the code to LIVE site.
