### ISSUE TITLE
Site is crashing in Chrome and IE, supposedly because of Sekindo ads

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#190]
see screenshot below for description. i haven't personally experienced this issue, but other HEthens are reporting it.

![screen shot 2015-12-02 at 10 36 06 pm](https://cloud.githubusercontent.com/assets/9164601/11552048/93374214-9945-11e5-8ba6-45a7495a90ee.png)

**Comment by jetlej** [comment]
Did we remove Sekindo yet? @MSchirp

**Comment by MSchirp** [comment]
@jetlej Im pretty sure we solved this issue with new tags, using iframe over javascript.
