### ISSUE TITLE
Bizarre page needs to be deleted or redirected

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#191]
No idea what is going on with these pages. I think they need to be deleted or redirected. 

http://www.highexistence.com/page/2/?cat=health-fitness
http://www.highexistence.com/page/5/?cat=psychology-happiness
http://www.highexistence.com/page/3/?cat=environmental

**Comment by jetlej** [comment]
Those show posts from categories and work as expected. Nothing wrong here.
