### ISSUE TITLE
Blocked Resources in Webmaster Tools

### ISSUE THREAD

**Issue by jetlej** [jetlej/HE-6.0-Bugs#192]
A number of domains, including our own CDN's, are showing up as blocked in Webmaster tools. The robots.txt doesn't show anything being blocked. 

![screenshot 2015-12-04 03 02 56](https://cloud.githubusercontent.com/assets/1179057/11591591/fc600236-9a66-11e5-9fbf-bad26cd64f90.png)

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej : I think this is something that you would need to resolve at your end : https://googlewebmastercentral.blogspot.in/2015/03/unblocking-resources-with-webmaster.html

We would require credentials if we have to fix this issue. Kindly let me know if we have to take it up. Thanks !

**Comment by jetlej** [comment]
@dpatil-gmcs - You can add the site to your own Google Webmaster account using FTP methods for verification

**Comment by dpatil-gmcs** [comment]
@MSchirp : We have provided our gmail account to you for granting us webmaster access. Let us know when done. Thanks !

**Comment by MSchirp** [comment]
@dpatil-gmcs This is done. Confirmed in Slack too.

**Comment by dpatil-gmcs** [comment]
@MSchirp  As per your comment, Closing the story.
