### ISSUE TITLE
when one adds a video, it no longer creates an image for the video

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#195]
i will still want to add videos sometimes, especially if i think they might blow up on social media. just tried and i was able to add a video, but it didn't create an image thumbnail for HE (and presumably not for social media). appears to be no way to add one either

**Comment by jetlej** [comment]
How did you add a video? Video submission is gone. 

I thought we were going to publish blog posts with videos and talk about them instead of posting videos anyways.

**Comment by lostboyevsky** [comment]
you can still add them in the backend.

we do want mostly to do the latter thing you said, but sometimes it's not really fitting to do that and much easier to just upload a video in the video area. the video in question that i uploaded reached over 65,000 people on FB when i shared it --- one of our best shares in the time i've been around --- so i'd say it was a good call to upload it. it wouldn't have made sense as an article, though. we should keep this possibility for such situations.

**Comment by jetlej** [comment]
@npadbidri - To fix this, you need to add thumbnail support to the video custom post type, and alter the theme so it first checks for a thumbnail, and only uses the 'video_thumbnail_url' field as a backup

**Comment by dpatil-gmcs** [comment]
@jetlej : 

This task is unclear to us. Can you give us more context on this issue : 

Questions : 
1. Assuming the Video is uploaded using "Add New Video", WHERE and HOW does the Video get consumed ? Meaning do we associate it in the POST ?

2. Do you mean that, you MIGHT have already SET a Thumbnail URL for the Videos and we need to give priority to The Thumbnail URL first and if not found then we fallback to the Video URL ?

3. Will the Site consume Videos that WE have control on ? This question is in context that we can use the Video Thumbnail plugin in that context.

4. Are you referring the "Video URL" whe you say video_thumbnail_url ?

From what we read, we need to ENABLE THUMBNAIL support while registering a Custom Post Type : 
https://codex.wordpress.org/Function_Reference/register_post_type
which should be done under Themes : hethen/admin/custom-post-types.php

We MAY have follow up questions on this one. Awaiting your comments on the same. Thanks !

**Comment by jetlej** [comment]
@dpatil-gmcs - Nevermind this bug, I have a solution.

@lostboyevsky - Just use the video submission form: http://highexistence.com/video-submission/

**Comment by lostboyevsky** [comment]
roger that
