### ISSUE TITLE
tagline needs to be changed back to 'Challenging the way you live!'

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#200]
for some reason it's changed back to 'daily boosts to your consciousness'

**Comment by jetlej** [comment]
@lostboyevsky - Not sure how you're seeing that. It has not changed for me

**Comment by lostboyevsky** [comment]
that's really wild. no one else is seeing it either, but i'm still seeing 'daily boosts.'

**Comment by jetlej** [comment]
Clear your cache. You must have the old image saved from before 6.0 launch
