### ISSUE TITLE
Sidebar Recommendations aren't showing #s 1, 2, and 6

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#201]
![screen shot 2015-12-14 at 9 40 46 pm](https://cloud.githubusercontent.com/assets/9164601/11801424/675a1742-a2ab-11e5-8af3-029b0921b581.png)
![screen shot 2015-12-14 at 9 40 35 pm](https://cloud.githubusercontent.com/assets/9164601/11801435/7a131b9a-a2ab-11e5-9440-b81bad71e8f3.png)

**Comment by jetlej** [comment]
@dpatil-gmcs - This is because I made it not output duplicate posts, but did not fix the count variable to not increase when a duplicate is found

**Comment by dpatil-gmcs** [comment]
Code has been committed to BeanStalk with Commit Hash : 8af7a31a
Please review the changes. If all looks good, we can close this issue. Thanks !

**Comment by MSchirp** [comment]
@jetlej Is there a way for me to learn how to verify the code and give the green light to make it live on the site?

**Comment by dpatil-gmcs** [comment]
@MSchirp : As recommended by @jordan we cannot deploy a particular (task specific) commit via BeanStalk. If you could sign off our changes on this task, we would be able to deploy #203 to Live Site immediately ?

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE
