### ISSUE TITLE
sidebar recommendations are being cut short -- can't read full titles 

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#202]
i think this is only the case for the sidebar on videos, images, and quotes. here's an example on a video:

![screen shot 2015-12-28 at 9 59 19 pm](https://cloud.githubusercontent.com/assets/9164601/12029354/93e672ca-adae-11e5-81ee-7f4ef523400b.png)

**Comment by lostboyevsky** [comment]
do you see what i mean by this? 

for instance, the bottom item in the side bar should say, "Rethinking Mental Illness: Are We Drugging Our Prophets and Healers?" but it costs it off at "and" . . . .

**Comment by dpatil-gmcs** [comment]
@lostboyevsky :
Code has been checked in to PROD Branch with Commit # : 8ce2221e
Now sidebar recommendations can read full titles.
Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by lostboyevsky** [comment]
Still seeing this issue. Check the sidebar on this image, for instance:

http://highexistence.com/images/view/whats-your-perspective-on-being-an-artist/

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @jetlej @MSchirp : 

Where are you testing the code meaning Stage / Prod ?
Ar ewe sure that the Commit we made : Commit # : 8ce2221e has been deployed to your Stage / Prod environments before you tested ?

We have no access hence cannot verify it. Let us know if the code has been deployed. Thanks !

**Comment by lostboyevsky** [comment]
@dpatil-gmcs To clarify, I'm testing these issues on the live site. I forgot that you were making the updates on the test site, so I can check there in the future. However, I just tried to check on this issue on the test site, and I found that the test site is totally messed up. I'm in Safari browser on a Macbook Pro, and this is what I see on the homepage and on an image page:

![screen shot 2016-01-15 at 2 12 41 pm](https://cloud.githubusercontent.com/assets/9164601/12366793/444a1040-bb92-11e5-92d0-79a570d2bb85.png)
![screen shot 2016-01-15 at 2 10 56 pm](https://cloud.githubusercontent.com/assets/9164601/12366792/4447aa44-bb92-11e5-9a35-0e28646c6d83.png)

**Comment by dpatil-gmcs** [comment]
@lostboyevsky : 
Someone from your end has to ADD the Staging domain via the admin which is when you will be able to test it on the Test Site.

As mentioned in comments on #184,  For your reference : 
@jetlej : Yes I agree with @MSchirp . The Sajari API FAILS and give an HTTP 401 meaning URL resource requires user authentication...I think the Staging Site domain is NOT authorized with Sajari. Hence the BLANK UI.

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE
