### ISSUE TITLE
SEO Link to Azarius only shows up when logged in

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#203]
The link under the Azarius ad only shows up when you are logged in. It should show up when you are not logged in too. See screenshots, bottom right:

Not logged in:

![highexistence challenging the way you live](https://cloud.githubusercontent.com/assets/13124056/12051898/a9456df4-af09-11e5-96b2-4444342e83a8.png)

Logged in:

![screen shot 2015-12-30 at 17 23 31](https://cloud.githubusercontent.com/assets/13124056/12053498/1ae94664-af1a-11e5-9209-bd5ecbfe9ee1.png)

**Comment by dpatil-gmcs** [comment]
Code has been checked in to PROD Branch with Commit # : 2bbd4518
Please let us know your cmments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by MSchirp** [comment]
@jetlej I just verified it doesn't show up when you are not logged in, yet this issue is closed. Is there an intermediate step I can take to finalise the change so it is working?

**Comment by lostboyevsky** [comment]
as a side note, i never once saw that Azarius banner on the live site. is that supposed to be there now? i've been seeing HE Resources banner for a couple months

**Comment by MSchirp** [comment]
@lostboyevsky It is geotargeted to Europe only. The resource banner is showing up for the rest. This reminds me that we should switch it between our store and our magazine.

**Comment by MSchirp** [comment]
@dpatil-gmcs Can you go ahead and push this fix to the live site? Please notify me on slack when it is up, thanks!

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej  : We have NO Access to PROD / Stage environment...Hence cannot help much on that front. However, if you are still seeing that the issue persists, can you confirm that the Commit # : 2bbd4518 has been deployed on Stage / Prod ?

**Comment by MSchirp** [comment]
@dpatil-gmcs I am not sure what you're asking. If you go to highexistence.com front page without being logged in, you can see the link is not showing up. Once you do log in, the link does show up. it is very important that it shows up ASAP. 

From what I've gather from @jetlej , you should be able to push the fix live to the website immediately. And I don't understand what I can do to make sure this happens. Could you clarify what you're asking? Thank you!

**Comment by dpatil-gmcs** [comment]
@MSchirp : 
We have pushed our changes to BeanStalk. Can you confirm that the line of code is present on the LIVE Site : https://highexistence.beanstalkapp.com/highexistence/changesets/2bbd4518588a062b739005bde85461aaeee2c739

If the code exists on LIVE Site, I recommend you to <b> PURGE Cache</b>

Secondly, <b>From what I've gather from @jetlej , you should be able to push the fix live to the website immediately</b> : We only have the authority to PUSH changes to BeanStalk from where you guys take up. 

@MSchirp : For your reference : The chat in SLACK dated 23rd Dec 2015 : 

This is what @jetlej has to say : <b>you can start by pushing to the production branch directly.
that will auto-deploy to the staging site.and then once we have approved those changes, we can manually deploy to the live site</b>

**Comment by MSchirp** [comment]
@dpatil-gmcs This can be pushed live asap.

**Comment by dpatil-gmcs** [comment]
@MSchirp : As recommended by @jordan we cannot deploy a particular (task specific) commit via BeanStalk. If you could sign off our changes on #201, we would be able to deploy this task to Live Site immediately ?

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE

**Comment by MSchirp** [comment]
@dpatil-gmcs I see that this link is suddenly no longer clickable. It is not just text. Please make sure it links to http://azarius.net/ , thank you!

**Comment by dpatil-gmcs** [comment]
@MSchirp  Made the link clickable, and also Updated the text as per your suggestion, The code is deployed to the LIVE site.
Tested at LIVE site, It is working as expected. Hence, closing the issue.
