### ISSUE TITLE
Infinite scroll on discussion replies and comments

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#205]
On discussions and comments we should have a cap of 10 comments or replies with a button-option at the end asking the user if they want to "load more".

**Comment by MSchirp** [comment]
To clarify, we have blog posts on which there are 50-100+ comments. Not every individual visiting these posts are interested in these comments. So we want to show a maximum of 10 comments, with a button  which says 'load more', which loads if clicked another 25. Preferably AJAX.

**Comment by dpatil-gmcs** [comment]
@jetlej 
This task will require work efforts of 2 to 4 hours.
Will keep you posted.
Thanks..!!

**Comment by dpatil-gmcs** [comment]
@jetlej @MSchirp : We cannot set variable numbers for fetching Comments. The plugin allows us to SET just 1 single value from Settings -> Forums -> Topics and Replies Per Page Section

We will HAVE to agree to a fixed number of Comments that will be fetched during LOAD and after Button Click. Please let me know your thoughts around the same. Thanks !

**Comment by jetlej** [comment]
@MSchirp

**Comment by MSchirp** [comment]
@dpatil-gmcs Gotcha. I think we should go ahead and show 5 before load, and everything else after load. 

If this includes threaded comments, then I think we should go with 10 before load, and everything else after load.

**Comment by dpatil-gmcs** [comment]
@MSchirp :
Code has been Deployed on Stage / Test site. Please let us know your comments if the enhancement looks good, that way we can CLOSE it. Thanks !

**Comment by MSchirp** [comment]
@dpatil-gmcs I can't find this enhancement. For instance, when I go to this page, I still see a lot of comments: http://hiexistence.com/8-books-for-a-higher-existence/

Can you direct me to a page on which it is working?

**Comment by dpatil-gmcs** [comment]
@MSchirp : This enhancement is on discussion replies and comments.
Following is the URL on which it is working.
http://hiexistence.com/topic/he-5-0-slogan-suggestions/ 
Thanks..!!

**Comment by JonBrooksX** [comment]
There are numbers AND a loading button. I would rather have one OR the other, not both.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX  @MSchirp : I have disabled the pagination for the replies i.e. only Load More button is  visible now,
The fix is commited to the PROD Branch with the commit #: 0b56b4fc.
Please have a look and push the change at live site.
Thanks..!

**Comment by MSchirp** [comment]
This looks great @dpatil-gmcs !

Two things:

1) Can you add this option also for blog posts? It is probably even more important for that, see my clarification above (second post of this issue.)
2) It is also showing 'load more' when there aren't anymore posts to load. A user will click on this, and then it says 'no more posts'. This builds anticipation but it doesn't deliver the goods, and hence, will be a letdown for them. Can you make it so that the button doesn't show up when there aren't more posts to load?

**Comment by dpatil-gmcs** [comment]
@MSchirp : Thanks ! We will have #1 implemented. 

However, for #2, we are NOT getting the callback from the plugin in case there are no posts. We will look into it.

**Comment by MSchirp** [comment]
Alright, keep me in the loop!

**Comment by dpatil-gmcs** [comment]
@MSchirp I have added the Load More option to the blog posts. The code is checked in to the PROD branch with the commit# : 34910b91
Please have a look and let me know your views on it, so that we can deploy it on LIVE site.

**Comment by MSchirp** [comment]
This doesn't seem to work on this page: http://hiexistence.com/this-will-mindfuck-you-videogame-ism/

Please advise.

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have implemented the Load More option on the following page: http://hiexistence.com/blog/ , as it was not clear from the requirements, Do you want me to revert those changes?
Tthe implementation on the the URL you provided, is bit different than other pages, we are researching on it.

**Comment by MSchirp** [comment]
@dpatil-gmcs Sorry, my mistake! It shouldn't be implemented on http://hiexistence.com/blog/ and neither on hi existence.com homepage. 

It should preliminary work on actual blog posts like the one I linked to.

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have removed the load more button and added the Infinite scroll on the  Home page and Blog page, I have also added the Load More button to the actual blog page as described by you.
This task is implemented and the changes can be seen on TEST site.
The code is committed to the PROD branch with the commit#: 466708a7
Please have a look and let me know your comments so that I can deploy the changes to the LIVE.

**Comment by MSchirp** [comment]
@dpatil-gmcs I just checked the blog post and it isn't working as it should yet.

The load more button should appear after 10 comments, and only apply to the comments. Now, it appears on the bottom after ALL comments, and it applies to the next blog post. 

This is what it looks now:

Blog post
all comments
load more button (that loads a new blog post)

This is what it should look like:

Blog post
10 comments
load more button (that loads more comments if you click on them)
infinite scroll new blog post (this should appear whether your click on load more or not)
10 comments
load more button
etc.

**Comment by dpatil-gmcs** [comment]
@MSchirp : This is my Understanding from the above comment:
1. Infinite scroll new blog post will be as it is on the blog post page.
2. Load More button must be applied only to the comments, where the comments are more than 10.

**Comment by MSchirp** [comment]
That sounds correct :)

**Comment by dpatil-gmcs** [comment]
@MSchirp  Looking at the code implementation, There is still a question about the task,
By 10 Comments, Do you mean 10 comments including their replies, or 10 comments without their replies?

Please find the attached Image, Here the first comment 'let’s do it agin' is the actual comment and the second one which says 'yeag yea ey' is the reply to first comment!

![screenshot from 2016-02-08 16 36 09](https://cloud.githubusercontent.com/assets/5171153/12885412/bd548f90-ce8b-11e5-940b-4038746872a4.png)

**Comment by MSchirp** [comment]
@dpatil-gmcs I meant 10 comments including their replies. (This is what I meant with 'threaded' above.)

**Comment by dpatil-gmcs** [comment]
@MSchirp Just so that you know, when we say 10 comments, wordpress gives us 10 comments and their replies too.
for example: Supppose if comments have 5 replies each, then when we say 10 comments wordpress will give us 10 comments + 5 replies per comment i.e. 50 comments.

**Comment by MSchirp** [comment]
Ok thanks, good to know! Lets go with 10 comments!

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have implemented this on TEST as well as LIVE site.
We had deployed the code yesterday, but the button was never visible because of misconfiguration of WP Admin settings, on both TEST and LIVE sites. so it took time for investigating the code and settings. Made it correct now, Tested on both LIVE and TEST site.
Please have a look and let me know your views on it, also please give us a sign off for the issue so that it can be closed!

**Comment by MSchirp** [comment]
Looks good @dpatil-gmcs !

Three little things:

- Could you change it from 10 comments to 5 comments? 
- Could you make the button 'load more' the same look as the ones on the homepage? 
- Could you make sure the button 'load more' be center on the page?

**Comment by dpatil-gmcs** [comment]
@MSchirp  Implemented the changes as per the above requirements and deployed the changes to TEST as well as LIVE site. Closing the issue!
