### ISSUE TITLE
Top right ad is being cut off

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#206]
Not sure why this happens, other people have brought it up and I can't replicate the issue. 

This is what he said "I saw it on chrome and Firefox browsers on a regular desktop screen without making any manipulation on the browsers (I checked it also with one of my colleagues - and we saw it on her computer also)."

See his screenshot:

![unnamed](https://cloud.githubusercontent.com/assets/13124056/12118630/d7993984-b3c7-11e5-9abd-adf7127cdf56.png)

I am doubting whether we could check if the issue is fixed on the test site, because the same tags aren't live there. @jetlej ?

**Comment by lostboyevsky** [comment]
i'm also unable to replicate the bug in chrome and safari

**Comment by dpatil-gmcs** [comment]
@jetlej :
This task will require work efforts of 1 to 2 hours.
Will keep you posted.
Thanks..!!

**Comment by dpatil-gmcs** [comment]
@MSchirp :
Ideally the best practice is to do css change in child theme. But as it is not in place, we did the changes in parent theme. Once the child theme is in place we will revert back our changes.

Code has been checked in to PROD Branch with Commit # : fcf39bb2
Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by MSchirp** [comment]
@dpatil-gmcs Is this fixed and deployed on live?

**Comment by dpatil-gmcs** [comment]
@MSchirp : We have deployed it on LIVE and it is working. Please verify that way we close the issue.
