### ISSUE TITLE
top navigation bar is showing the old tagline

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#207]
It now reads 'Daily boosts to your consciousness', while it should read 'Challenging the way you live'.

See screenshot:

![screen shot 2016-01-05 at 16 47 42](https://cloud.githubusercontent.com/assets/13124056/12119463/432fc86c-b3cc-11e5-8370-97e0f8d75e93.png)

**Comment by lostboyevsky** [comment]
so weird. it did the same thing for me about one month ago, but now mine is changed back to "challenging ..." . . . . no idea what's going on with that

**Comment by MSchirp** [comment]
@jetlej thoughts?

**Comment by jetlej** [comment]
There is no trace of that old version on the server. I can only imagine it's some weird caching thing, but even that seems farfetched. 

What do you see when you go here?

http://highexistence.com/wp-content/themes/hethen/images/logo@2x.png

**Comment by MSchirp** [comment]
I see daily boosts to your consciousness. @jetlej

**Comment by jetlej** [comment]
Whatttt. So weird. It must be Cloudflare then. Emptying that cache now.

**Comment by jetlej** [comment]
@dpatil-gmcs - Please append a ?v=6 to the image URL in the header to make sure this is fixed for everonye

**Comment by lostboyevsky** [comment]
@jetlej when i go to that link i see "challenging the way you live!"

**Comment by dpatil-gmcs** [comment]
@MSchirp :
Code has been checked in to PROD Branch with Commit # : 845efae2
Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by MSchirp** [comment]
This one was fixed by @jetlej , sorry for not closing earlier!
