### ISSUE TITLE
front page above-fold ad spot is showing an 'image error' icon *in Google Chrome*

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#209]
it's not happening in Safari

look at bottom right:

![screen shot 2016-01-06 at 4 05 51 am](https://cloud.githubusercontent.com/assets/9164601/12140116/dba3b3c0-b42a-11e5-84b0-5f00a49c83ec.png)

**Comment by MSchirp** [comment]
This is probably not an issue on our side. I checked our ad server and the image loads properly. Please confirm it's still not loading properly, I can't replicate the issue.

**Comment by MSchirp** [comment]
@lostboyevsky

**Comment by jetlej** [comment]
It looks fine to me

**Comment by lostboyevsky** [comment]
@MSchirp working fine for me now
