### ISSUE TITLE
Lots of comments not showing up under blog posts

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#210]
For example, this blog post had dozens of comments below. Now it only shows 4. 

http://highexistence.com/how-porn-rewires-the-brain-is-porn-bad-for-you/

**Comment by dpatil-gmcs** [comment]
@MSchirp : Ensure that the Checkbox for "Break comments into pages with  top level comments...."under Wp Admin -> Settings -> Discussion" is UNCHECKED...That causes only the LAST few comments to be displayed.

**Comment by MSchirp** [comment]
Awesome @dpatil-gmcs , this fixed it, thanks!
