### ISSUE TITLE
Can't log in to http://www.highexistence.com/wp-admin/ anymore, shows a blank page

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#211]
This page is not loading at all. No error. Just a blank page for me: http://www.highexistence.com/wp-admin/

**Comment by MSchirp** [comment]
@dpatil-gmcs can you make this your highest priority now?

**Comment by dpatil-gmcs** [comment]
@MSchirp : 
Accessing the wp-admin URL redirects me to : http://highexistence.com/signin/?redirect_to=http%3A%2F%2Fhighexistence.com%2Fwp-admin%2F&reauth=1

Do you mean POST Login you see a BLANK Page ?

**Comment by MSchirp** [comment]
@dpatil-gmcs 

I don't know what PROD FTP / SSH Credential are. Can you tell me how to get these for you?

1) No, just visiting that link gives me a blank page. I can't access the wordpress back end in any way.
2) Not that I am aware of. @lostboyevsky & @JonBrooksX ?

**Comment by dpatil-gmcs** [comment]
@MSchirp : 
Screenshot : http://screencast.com/t/qFewdqVuPI3

We have tried hitting http://www.highexistence.com/wp-admin/  LINK from 3 different computers and we are successfully redirected to the Login Page...So it is NOT reproducible for us.

1. Can you try clearing your <b>browser cache OR launch the browser in INCOGNITO Mode </b> and try to hit the same URL ?

2. If #1 does not work for you, can you RECORD the network traffic on your browser for us and attach it here, that way we can analyze it ? 

To capture network traffic : Launch GC in Incognito Mode -> Press F12 -> Go to Network Tab -> Press Ctrl + R to record traffic and then hit the wp-admin URL in the GC Browser.


Awaiting your response. Thanks !

**Comment by MSchirp** [comment]
Just tried again and the page is now working. However, I still can't log in.

**Comment by MSchirp** [comment]
I just followed your steps. How can I get the data to you?

**Comment by MSchirp** [comment]
![screen shot 2016-01-12 at 13 03 48](https://cloud.githubusercontent.com/assets/13124056/12263117/f44a60ac-b92c-11e5-86de-18e49d4349c0.png)

**Comment by jetlej** [comment]
@dpatil-gmcs - The login page loads fine, but after you login you get a 500 error
