### ISSUE TITLE
Removal of all AJAX pages (includes infinite scroll on discussion) discussion

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#213]
Yo all;

We removed the opening of blog posts in AJAX from the front page some months ago. 

The reason for this was twofold: 1) ads don't show up on AJAX pages & 2) recommended blog posts sidebar doesn't show up on AJAX pages.

Do we want remove this for infinite scroll on blog posts too? Right now, the advantage is that it automatically opens up a new blog posts and that will probably improve engagement. However, this might not be as big with other sites since our blog posts take more time and effort to digest. 

The disadvantage is that we can't show ads on them and that the engagement from the next post is lower due to missing recommended blog post sidebar. 

Thoughts? I guess that it slightly improves engagement, but lowers ad income to keep it. And vice versa to remove it.

@JonBrooksX @lostboyevsky

**Comment by MSchirp** [comment]
@dpatil-gmcs Our 'sekindo' advertiser is getting traffic from both 'highexistence.com' as from 'default'. The only explanation I can think of is that a percentage of their advertising is getting loaded in AJAX, and that this messes up the source of the traffic somehow. 

Quick question, can you confirm this is the case? And if it is, is there an easy way to prevent this from happening? Or would you recommend taking AJAX loading off altogether as I proposed in this issue #213 ?

If it is not, do you know any other explanation that might cause this?

**Comment by MSchirp** [comment]
See attachment:

![image002](https://cloud.githubusercontent.com/assets/13124056/12354055/8ef82252-bb93-11e5-99a2-877279748e85.png)

**Comment by JonBrooksX** [comment]
From what you've said Martijn I can't see any benefit in making changes. It seems like it would more or less equal out. So for that reason I would say there is no need to change this right now and instead we could work on something which has a clear, substantial benefit.

**Comment by lostboyevsky** [comment]
is there a way to A/B test this to find out how recirculation numbers and ad revenue compare for infinite scroll versus no infinite scroll?

**Comment by MSchirp** [comment]
@lostboyevsky Too complex I think. The sekindo issue is fixed, so I suggest we leave it be as is for now.
