### ISSUE TITLE
People are unable to log in

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#215]
You can push a fix directly. Check http://highexistence.com/signin/?redirect_to=/

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej : 

I am sorry but as we have been saying that We can just reproduce it on LIVE (Click Sign In Link -> Redirects to the above link) but cant help much on that (as locally it is not reproducible)...Also, we do not have a background on what the current LIVE Site has (meaning plugins : active / deactive, etc.).

Also looks like the shortcode <b> [theme-my-login]</b> has not been rendered on the sign in page, meaning some plugin is deactivated and hence the page looks BLANK...We will try to find online what plugin renders this Shortcode OR is it our own custom shortcode.

Will keep you posted. Thanks !

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej :
The "Theme My Login" plugin was ACTIVATED all this while and deactivating the plugin has caused this issue. Activating the plugin should resolve this issue.
Let me know if all looks good by activating the plugin. 
Thanks !!!

**Comment by MSchirp** [comment]
This fixed it, thanks :-) should have figured that out myself, silly me
