### ISSUE TITLE
Recommendation widget sidebar : mail from their support

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#217]
I am just copying their mail here and add my own comments @dpatil-gmcs :+1: 

One problem i see is that the recommendations are loaded regardless of them being viewable, which they aren't on many devices as they are outside the main body container. So that will really impact the CTR

@dpatil-gmcs Can you make it so that the recommendations aren't loaded when the page is under a certain size? 

You have a custom integration as well, which is fine, but it omits "onmousedown" click tracking. This is typically ok as we can pick up the click on the following page as well, but some technologies clean the tracking parameters from the URL, so we find it's better to use both. We actually are going to change this to a redirector soon as it cleans this up without changing the destination URL.

@dpatil-gmcs Not sure what this means. We should probably just wait? What are your thoughts?

There are "console.log()" and some other functions that may trip up older browsers and cause JavaScript errors such that the recommendations don't display (i haven't checked if you polyfill, but just noting)

@dpatil-gmcs Not sure what we can do with this either.

Either way, here are their recommendations:

1. Only inject the recommendations if the div is going to be visible
2. Get the onmousedown event up and running. You can try to use the prebaked HTML widgets and style them as needed, or we can provide you details on what to add.
3. Add a polyfill for console or remove it.

**Comment by dpatil-gmcs** [comment]
@MSchirp : 
For <b>Add a polyfill for console or remove it.</b> we have REMOVED Console logs.

For <b>Only inject the recommendations if the div is going to be visible</b> previously code was injected in DOM and was set to invisible...Now we LOAD the script in DOM only when DIV needs to be visible. 

When you say <b>Get the onmousedown event up and running. </b>, I assume you want to TRACK the page /post analytics...What code needs to be put in is unknown. Can you provide us that OR confirm with the Sajari folks of what needs to go in there ?

Awaiting your response on this one. Thanks !

**Comment by mish15** [comment]
@dpatil-gmcs hi there! The function to do this is:
```
SJ.SendClick(qid, slot, injected, node);
```

Where:
"qid" - is the string based query id returned with the results
"slot" - is an integer representing the result slot. e.g. first result is 1, second is 2, etc.
"injected" - you can leave this as an empty string.
"node" - is the current node to bind the event to. So we would normally put this on the <a> element.

Example:
```
onmousedown="SJ.SendClick("abcdefghijklmnopqrst", 2, null, this);"
```

**Comment by dpatil-gmcs** [comment]
@MSchirp :
Code has been checked in to PROD Branch with Commit # : 595b272b
Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE
