### ISSUE TITLE
Add a link to the store to the top navigation bar without messing up design

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#218]
I hope I can explain this issue correctly.

Right now, the top navigation bar looks like this:

![screen shot 2016-01-14 at 15 32 48](https://cloud.githubusercontent.com/assets/13124056/12326977/2cbbafb0-bad4-11e5-82ba-9d648a292469.png)

When you reduce the width of your browser, it will look like this:

![screen shot 2016-01-14 at 15 33 00](https://cloud.githubusercontent.com/assets/13124056/12326988/383a20ce-bad4-11e5-8e1e-07a3b47bb74b.png)

As you can see, the Facebook like button disappears. 

Now, we want to add a fourth item, on the right of 'about', called store, linking to store.highexistence.com
The problem is, when we do this manually in the wp-admin, it messed up the design. We tried to add "evolve' to the bar some time ago, and that looked like this:

<img width="1032" alt="screen shot 2015-11-15 at 10 38 47 am" src="https://cloud.githubusercontent.com/assets/13124056/12327044/89688cc4-bad4-11e5-9e6a-045c61f5c89b.png">

You can see that the bar is doubled because there isn't enough room. So we want the 'store' item to the bar, but we want that it disappears just like the Facebook like button when the width of the browser gets smaller (right around the point where the doubling happens.)

**Comment by dpatil-gmcs** [comment]
@MSchirp :
Code has been checked in to PROD Branch with Commit # : 9fc6e6fe

<b> Following things Must be done BEFORE DEPLOY this 
1. Add store as a custom link in menu 
Goto wp-admin -> Appearance -> Menus 
Find custom links option and add link to menu 
2. Save menu changes 
3. Once you have created the link then only deploy the code on Stage / Prod </b>

Please let us know your comments if the issue has been fixed, that way we can CLOSE it. Thanks !

**Comment by MSchirp** [comment]
@dpatil-gmcs How can I deploy the code?

**Comment by MSchirp** [comment]
When you change the width of your browser, at some point the bar doubles again, see screenshot:

![screen shot 2016-01-21 at 14 58 52](https://cloud.githubusercontent.com/assets/13124056/12482421/a9a1f306-c04f-11e5-9141-a38da695823b.png)

@dpatil-gmcs

**Comment by dpatil-gmcs** [comment]
@MSchirp 
I have hidden the Store menu item, whenever the bar gets doubled.
The code is committed to the PROD branch as commit #: 8951e929
Please have a look and let me know your comments.

**Comment by MSchirp** [comment]
I just checked, and it is still doubling on LIVE.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Did you deploy it to LIVE? I just had a look at LIVE site, the code has not yet reflected.

**Comment by dpatil-gmcs** [comment]
@MSchirp : Changes deployed on LIVE Site and working as expected. Pelase verify that wya we can close this issue. Thanks !

**Comment by MSchirp** [comment]
@dpatil-gmcs Works like a charm, thanks!
