### ISSUE TITLE
Formatting issue with 'list' articles

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#219]
See screenshot and this page:

http://highexistence.com/18-thought-provoking-questions/

![screen shot 2016-01-15 at 13 54 12](https://cloud.githubusercontent.com/assets/13124056/12353450/a95bac76-bb8f-11e5-86e3-ee5788d9b7f1.png)

Perhaps something changed with the plug ins @jetlej ?

**Comment by JonBrooksX** [comment]
fixed
