### ISSUE TITLE
Update Wordpress new version test site

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#220]
:-)

**Comment by dpatil-gmcs** [comment]
@MSchirp :
It is a MAJOR Check-in / Feature I am creating a new Branch for this and doing the Upgrade manually since NO WP Admin credentials.
Thanks..!!

**Comment by MSchirp** [comment]
@dpatil-gmcs I can give you wp-admin credentials for hi existence.com, one second.

**Comment by dpatil-gmcs** [comment]
@MSchirp : Recieved thanks :)

**Comment by dpatil-gmcs** [comment]
@MSchirp : Have you took the stage (test) site back up?

**Comment by MSchirp** [comment]
@dpatil-gmcs I don't understand your question, could you elaborate?

**Comment by dpatil-gmcs** [comment]
@MSchirp : It is recommended to take a Back up before updating wordpress. So the question was, Did you take the stage site Back Up ?

**Comment by MSchirp** [comment]
Nope, I did not. Check my latest message in slack! :)

**Comment by dpatil-gmcs** [comment]
@MSchirp : I have replied to your comment on Slack.

**Comment by MSchirp** [comment]
@dpatil-gmcs Can this be closed?

**Comment by dpatil-gmcs** [comment]
@MSchirp : Test Site upgraded to WP 4.4.2..We can close this one. Thanks !

NOTE : WP Live is still Version 4.4.1
