### ISSUE TITLE
some problems with screen that comes up when not signed in and click "reply" or try to upvote in discussions

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#221]
when i click "reply" or try to upvote a comment and am not signed in, i get this screen: 

![screen shot 2016-01-19 at 11 23 33 am](https://cloud.githubusercontent.com/assets/9164601/12429511/819080dc-be9f-11e5-95ff-db4d224d131f.png)

for one, the screen says "Create Account OR," but the "OR" is nonsensical because there is only one option given: the option to create an account. i think this screen should give one the option to log in or create an account.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky : There was a Facebook Login option present before (LOCAL Code still shows the facebook login)...Probably, someone has REMOVED / DEACTIVATED the Plugin that displayed the facebook login option. 

@MSchirp Do we want to look at getting the FACEBOOK Login back or just remove the "OR"  text ?

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp :
The "Super Socializer" plugin was ACTIVATED all this while and deactivating the plugin has caused this issue.
Time invested : 20 Minutes

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp : Any specific reason why this plugin was deactivated ? Also do we need the facebook login in first place ? 

If we need the facebook login to show up, then activating the above mentioned plugin resolves the issue. If not then we will have to remove the text from the UI. Let us know your thoughts around the same. Thanks !

**Comment by MSchirp** [comment]
@dpatil-gmcs This was probably due to the crash. The Facebook log in needs to show up.

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE
