### ISSUE TITLE
not all posts are loading on my user page

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#222]
go here: http://highexistence.com/people/bashfulkoala/posts/

i'm only seeing my 10 most recent posts here. i should be able to look through all of my post history

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp :
This issue has been fixed. Code has been committed to BeanStalk with Commit : #7a69077a
We have also checked in code for the bug introduced by us in #208 which we had fixed previously. 
We observed that <b>Favorites link : http://highexistence.com/people/bashfulkoala/favorites/</b> too displays 10 posts only, do we want it to also display ALL Posts or it looks good as is ?

**Comment by MSchirp** [comment]
@dpatil-gmcs Awesome!

Favorites links should show ALL posts that have been favourited by a user, thank you!

**Comment by dpatil-gmcs** [comment]
@MSchirp : Deployed on LIVE
