### ISSUE TITLE
A user's comment and discussion history doesn't show up on their profile

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#223]
See for example this user:

http://highexistence.com/people/abigailwyatt03/posts/

I can see from here that this user posted the most lately: http://highexistence.com/discussions/ (see discussions leader)

But I think this might have been a lot of spam. Preferably, we want to see people's complete history on that page.

**Comment by dpatil-gmcs** [comment]
My understanding on issue: 
On user profile page you want to show user's comment and discussion, But when I tested it in local I found we are showing discussion.
And yes we does not show users comment on user profile page.

Queries:
1. How we are planning to show user's comment? I mean if user has given a comment on any post / topic, Does that post / topic is also shown on user's profile? 

Please share your thoughts on same.
Thanks !!!

**Comment by MSchirp** [comment]
@dpatil-gmcs 

1) Yes, any comment on both discussion or blog post should be visible on their history. Does that make sense?

**Comment by dpatil-gmcs** [comment]
@MSchirp Looking at the code implementation, the Dashboard leaders list is populated with the 'Top commentors of the week'.

Do you mean you want to add a new field on the user's profile which lists out the comments on both Discussion and Blog?

**Comment by MSchirp** [comment]
Yes :)

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have implemented the comments tab for the user profile on my localsite. Please have  a look at the attached screen shot and let us know if you want us to implement on TEST and LIVE site, with the same look and feel or do you want some changes in look and feel.
NOTE:
1. Date can be formatted if needed.
2. The UI is not like other tabs, because the other tabs show posts/video/images so they have a thumbnail to display while comments does not have any image.
![user_comments](https://cloud.githubusercontent.com/assets/5171153/13396464/a82445f8-df1a-11e5-9514-4f47eb1ca89a.png)

**Comment by MSchirp** [comment]
Looks good, please implement it in TEST! Thanks!

A few little things: 

- The 'Posts' tab should be renamed to 'History'
- The tabs All, Links, Videos, Images  & Quotes should be removed.
- The order of showing tabs should be changed to 'Comments, Discussions, Blog Posts'. And Comments should open first thing when opening the 'History' tab.

**Comment by dpatil-gmcs** [comment]
@MSchirp  This issue is commited to the test site, and you will be able to see the changes as soon as the test site is up.

**Comment by MSchirp** [comment]
Noted

**Comment by dpatil-gmcs** [comment]
@MSchirp  Now that the TEST site is up, please have a look at the implementation and let us know your views on it so that we can deploy it on LIVE site.

**Comment by MSchirp** [comment]
@dpatil-gmcs This looks good! 

Just for your info: on the test site users are called /members/, in LIVE site they are called /people/. I don't know why this is.

Two more little changes:
- In the third section in History, it says 'Post Link'. This should be renamed to 'Post'. 
- All the links themselves are called 'View Post'. These should have the actual title of the discussions or blog posts.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Implemented the change and commited the code to TEST site. Please have a look and give us a sign-off so that we can deploy the code on LIVE site.

**Comment by MSchirp** [comment]
Looks even better @dpatil-gmcs !

A few more things:

- Posted on,  Comment, & Post texts should be a bit bigger text than the rest of the text.
- Posted on should include the time zone it is using to report the time. So the text should say 'Posted on (MST+0)'
- The width of the column 'Posted on' is too wide. It should be about as wide as the date + time width. The width of this data won't change ever.
- Between the date and the time should be a @. So, 2016-03-08 @ 06:53:26

And a question. It doesn't seem to load all users comments. It loads a long list, but it suddenly stops. I think this list can be shortened a bit, and then have the 'load more' button to load another batch. Or have the infinite load solution. Thoughts?

**Comment by dpatil-gmcs** [comment]
@MSchirp  we have implemented the changes suggested by you, and committed the code to the TEST site. Please have a look and let us know your views on it.
Can you please provide the profile/url for which you found that it doesn't show all the comments.
We did not implement the button or infinite scroll as none of it was implemented in any of the parallel tabs.

**Comment by MSchirp** [comment]
@dpatil-gmcs This looks fantastic, well done!

I was mistaken that it doesn't show all comments. Please disregard that point.

Last few things, I promise haha!

- Please center these header texts: Posted on (UTC-7), Comment, Post
- Please increase the width a little between Comments and Posts columns.
- Its fine that the text loses some of its format. However, right now it also loses when a sentence should be on the next line or not. This way, all different paragraphs are removed, which makes reading difficult. 

For example, see my comment section, especially my longer comments, and you will find huge slabs of text with no make up. Would it be possible to include paragraphs/next lines?

http://hiexistence.com/members/martijn-schirp/posts/

**Comment by dpatil-gmcs** [comment]
@MSchirp  we have made the changes and commited the code to TEST site, Please have a look and give us a sign-off so that we can deploy it on LIVE site.

**Comment by MSchirp** [comment]
It seems it doesn't show paragraphs yet, see screenshot:

![screen shot 2016-03-10 at 13 29 59](https://cloud.githubusercontent.com/assets/13124056/13669508/48b20766-e6c4-11e5-9342-0bc54a032eed.png)

**Comment by MSchirp** [comment]
You can push this live too once the paragraph issue is resolved.

Quick question, what kind of dependency is there with #246? they seem very unrelated.

**Comment by dpatil-gmcs** [comment]
@MSchirp  When we deploy the code from TEST site to LIVE site, we must deploy in the same order we push the code to TEST site. So there is dependency. Also #187 depends on #223 for deployment.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Made the required changes, and I have pushed the code to the LIVE site. Hence closing the issue.
