### ISSUE TITLE
Weekly Mail not Showing HTML on mobile phone

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#224]
![img_0863](https://cloud.githubusercontent.com/assets/13107838/12552140/c85d5f4a-c367-11e5-8cc5-5c26e3fc3a6e.PNG)

The weekly mail looks fine on desktop but I was sent this on mobile. Looks like there's no HTML formatting.

**Comment by JonBrooksX** [comment]
Just ran a test and everything seems to be fine. I sent it to you too @MSchirp. Can you confirm that the weeklymail is fine on mobile?

**Comment by MSchirp** [comment]
Seems to work fine for me.
