### ISSUE TITLE
seeing the featured images blanked out for some of the items in the recommendation sidebar

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#225]
note the blanked-out image for '50 life secrets & tips':

![screen shot 2016-01-26 at 2 54 51 pm](https://cloud.githubusercontent.com/assets/9164601/12598071/0449fca4-c43d-11e5-80d2-bfe89793c032.png)

**Comment by lostboyevsky** [comment]
update: also seeing that some featured images are displaying the wrong image. the image for 'SUBLIME DEATH' is wrong in this picture:

![screen shot 2016-01-26 at 5 07 13 pm](https://cloud.githubusercontent.com/assets/9164601/12600527/678949ac-c44f-11e5-98fb-b7525741a4ac.png)

**Comment by lostboyevsky** [comment]
another update:

i'm also seeing "-- High Existence" added to the end of some post titles in the recommendation sidebar for quotes/videos/images. this should not appear. see below:

![screen shot 2016-01-26 at 5 13 49 pm](https://cloud.githubusercontent.com/assets/9164601/12600664/4f47342a-c450-11e5-8dd0-c5b6792f7394.png)

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp @jetlej : 
I think Issue #226 is linked to this one...We are working on NOT INDEXING the Stage Site...This fix should resolve both the issues..Will update you once done.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @jetlej @MSchirp :
I have added the ranking rule in sajari to omit all pages from stage/test site domain.

**Comment by MSchirp** [comment]
Verified fixed, great job! @dpatil-gmcs

**Comment by lostboyevsky** [comment]
@MSchirp please open this issue back up, or else show me how i can do that. it looks like a couple of these issues have been resolved, but i'm still seeing some missing images. taken just now:

![screen shot 2016-01-27 at 8 40 47 pm](https://cloud.githubusercontent.com/assets/9164601/12635326/e83cdf04-c536-11e5-9df7-1c7d9f05810e.png)

**Comment by JonBrooksX** [comment]
Have you flushed your browser cache @lostboyevsky ? Do that and try again to make sure.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp 
I found that the missing images are not present on the CDN. For example : http://1.hiexistence.com/wp-content/uploads/2016/01/war-comic-600x315.png is missing for the following POST : http://highexistence.com/the-sniper-mind-bending-comic-on-the-nature-of-life-death-war-morality/

**Comment by MSchirp** [comment]
@dpatil-gmcs It shouldn't load that 'missing image', because that leads to hiexistence.com, NOT highexistence.com.

**Comment by lostboyevsky** [comment]
It seems that I am no longer seeing blanked-out featured images. @dpatil-gmcs, this appears to be fixed.
