### ISSUE TITLE
URGENT: All links in sidebar on HE are linking to the test site, HiExistence.com.

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#226]
all sidebar recommendations on the site are directing traffic to the test site. this is a significant detriment to recirculation of traffic and needs to be fixed asap

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp @jetlej : 
I think Issue #225 is linked to this one...We are working on NOT INDEXING the Stage Site...This fix should resolve both the issues..Will update you once done.
