### ISSUE TITLE
Mail template cutting off titles

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#227]
Hey Deepak, I will invite you to our mail chimp account soon for this issue and issue #224 .

Our e-mail template we use in MailChimp loads the information from our rss feeds. But it cuts off the title, as you can see in the following screenshot: 

![screen shot 2016-01-27 at 17 25 47](https://cloud.githubusercontent.com/assets/13124056/12620519/e331a090-c51c-11e5-95b1-bf22aeb787ba.png)

See "...We All Face..." . It cuts off and adds 3-dots to the end, while it should be "... We All Face Between Aspiration and Accomplishment"

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have visited mail chimp account and I found that we use newsletter 6.0 template for the newsletters, I have researched at mail chimp but couldn't find any Title related code.

I will need to investigate some more at this, and try to find why the title is being cut off.

**Comment by dpatil-gmcs** [comment]
@MSchirp   There is a setting in HE Options 'Listing Title Max Length' Which was set to 70, I have changed it to 1000 and looks like the full title is visible now.
Please have a look and let us know your views on it.

**Comment by lostboyevsky** [comment]
@JonBrooksX can you look at this to make sure it's working correctly? I have never done much with the Mailchimp account.

**Comment by dpatil-gmcs** [comment]
@MSchirp @lostboyevsky @JonBrooksX  Any updates for us?

**Comment by MSchirp** [comment]
Looks good, closing!
