### ISSUE TITLE
Scroll bar goes up into the nav bar

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#231]
![screenshot 2016-01-31 21 14 39](https://cloud.githubusercontent.com/assets/13107838/12705018/f7de6e10-c85f-11e5-8749-74d5c84dcb11.png)

This persists across all user submitted content types: videos/links/images.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX 
Do you still see this happening ? OR it occurs very rarely ? We are unable to reproduce it on any environemtns : Local / Test Site / Live . Please let me know your comments and steps to reproduce (if any). Thanks !

**Comment by JonBrooksX** [comment]
I haven't seen it since @dpatil-gmcs I think we can close this issue now
