### ISSUE TITLE
short code [related url=“http://highexistence.com/50-life-secrets” title=“50 Life Secrets & Tips”] is not working

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#233]
This was a custom shortcode Jordan defined in functions.php, we use it in blog posts to add an extra manual link to another article we feel the reader wants to read next

**Comment by dpatil-gmcs** [comment]
@MCShirp : 

Can you direct me to the POST URL where you wish to use this one ? The above line just needs to be placed on the POST and it should work. As it is working on our LOCAL Setup. If this code was used and if it had not worked the same CODE would have displayed on the particular post.

Seems like we have not yet used it in any post. 

Let me know your observations. Thanks !

**Comment by MSchirp** [comment]
@dpatil-gmcs I used two of these codes in this article: http://highexistence.com/gift-of-the-gods-why-visionary-plant-medicines-deserves-reverence-and-caution/

Not working on live.

**Comment by dpatil-gmcs** [comment]
@MSchirp 

May be the shortcode was copy pasted via some HTML Text Editor, hence the issue.

The problem with the code was, earlier while adding the code the qoutes used were (“ ”).
I just changed them to be simple quotes like " "  and the above code started working. The shortcode now looks like:
[related url="http://highexistence.com/the-poet-rilkes-uncommon-wisdom-on-love-relationships/" title="The Poet Rilke’s Uncommon Wisdom on Love &amp; Relationships"] 

I have reflected the changes for the article which you had provided, and You can see the change at: http://highexistence.com/gift-of-the-gods-why-visionary-plant-medicines-deserves-reverence-and-caution/

Please have a look and let us know your comments, that way we close the issue. 
NOTE : Please  ensure the quotes are as mentioned above for the shortcode to work properly.

**Comment by MSchirp** [comment]
Awesome, looks great!
