### ISSUE TITLE
Bottom-of-post ads on mobile are long, horizontal ads that extend past page border

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#236]
Our top-of-post ads on mobile are correct: rectangular, near-square ads that fit within the mobile UI borders. I just noticed, though, that our bottom-of-post Adsense ads are not the correct size. They are long, horizontal rectangles that extend off of the page by a lot. I'm not sure how long this has been this way, but this could be a quite significant change --- it will make those ads much more prominent, legible, and clickable.

**Comment by MSchirp** [comment]
Fixed.
