### ISSUE TITLE
Add slots for advertisements on Video/Image pages

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#237]
Martijn and I have decided that we think it would be a good idea to serve more ads on Video/Image pages (e.g. http://highexistence.com/videos/view/sam-harris-on-meditation-and-consciousness-2/).

The ad slots should be the same as those in which we serve ads on Blog Post pages --- long, horizontal rectangles on desktop and near-square boxes on mobile. For Video post ads, one ad should appear above the video and one ad should appear directly above the box in which users can type comments. For Image post ads, one ad should appear directly below the title (the title appears above the image, whereas for videos it appears below), and one ad should appear directly above the box in which users can type comments.

**Comment by MSchirp** [comment]
@lostboyevsky Could you add some screenshots on what exactly you want and where?

**Comment by lostboyevsky** [comment]
@dpatil-gmcs, here are some screenshots to show more specifically where I mean the ads should go. 

Below title on Image posts

![ad1](https://cloud.githubusercontent.com/assets/9164601/13033433/dae39f68-d2ca-11e5-98e4-05ee02467c59.png)

Above video on Video posts:

![ad3](https://cloud.githubusercontent.com/assets/9164601/13033438/e9577a92-d2ca-11e5-828e-0ac1e953855e.png)

Directly above box in which users type comments on both Video and Image posts: 

![ad2](https://cloud.githubusercontent.com/assets/9164601/13033440/f9e90114-d2ca-11e5-9842-e64e1c1d4cde.png)

And then on mobile all of these ads will be in the same positions, but they will be different sizes (almost-square rectangles) appropriate for mobile. So the containers created for desktop and mobile should be appropriate for those sizes.

**Comment by MSchirp** [comment]
@lostboyevsky The size-responsive ads will be determined from our ad code, not hardcoded in the site. 

@dpatil-gmcs Just copy the exact same manner Jordan implemented these for blog posts. So the box of 
'**Blog Post - Above Blog Text Ad Embed Code**' in HE options in WP-admin should go above image and video page too, in the same way as in a blog post.

And the box of '**Blog Post - Below Article Ad Embed Code**' should go below the image and video page too. In the same way as in a blog post and as @lostboyevsky indicated with the red boxes.

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have added the code  on Video and Image page as per the requirement and committed the code to the TEST site. This can be only tested on LIVE site as the ADs are only visible on LIVE.
To deploy the code on LIVE site, we need a sign off for #244 and #245.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Deployed the code to LIVE, Tested, the ADs and looks good Hence closing the issue.

**Comment by lostboyevsky** [comment]
looks great, @dpatil-gmcs. thank you. : )
