### ISSUE TITLE
Add Facebook and Twitter share buttons to the bottom of all post types

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#239]
Currently, these Mashable-style FB and Twitter buttons only appear on Image posts. Like this:

![screen shot 2016-02-08 at 4 17 49 am](https://cloud.githubusercontent.com/assets/9164601/12885468/0faecf24-ce1b-11e5-996d-0150088eb909.png)

I think it would be wise for us to add these buttons to the bottom of all post types --- blog posts, videos, and quotes, in addition to images.

**Comment by lostboyevsky** [comment]
@MSchirp, do you agree with this?

**Comment by MSchirp** [comment]
@lostboyevsky Where exactly? The bottom of the page is already quite full.

**Comment by lostboyevsky** [comment]
either directly above or directly below the 'Loved This' button . . . i don't think this would add a significant amount of clutter, and if it increases our shares in any significant way, it would probably be worth it. what you think, @JonBrooksX ?

**Comment by JonBrooksX** [comment]
The "love this" button on posts is not centered as it is in the image posts, and I don't think it would look as nice. 

I think share buttons to the LEFT of the "love this" button would work though.
