### ISSUE TITLE
In discussion, adding a hyperlink through the editor, has a bug.

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#24]
See screenshot:

![screen shot 2015-07-10 at 22 50 38](https://cloud.githubusercontent.com/assets/13124056/8628885/c9851d48-2756-11e5-8363-e99eb5d99d2c.png)

**Comment by MSchirp** [comment]
This is safari btw.

**Comment by jetlej** [comment]
Fixing on live site too :)
