### ISSUE TITLE
When adding a hyperlink in a discussion, the popup to enter a link is messed up

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#242]
This is what I'm seeing when I click the hyperlink button (notice the 'Insert' button is being cut off):

![screen shot 2016-02-08 at 4 16 19 pm](https://cloud.githubusercontent.com/assets/9164601/12903837/ad3a54ac-ce7f-11e5-9055-28510f5ce336.png)

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp  This issue is not repoducible on STAGE and LIVE site, Has some body edited the bbpress plugin? Please let us know if some one has activated any new plugin or made changes to existing one!

**Comment by MSchirp** [comment]
@dpatil-gmcs Nobody knows how to edit the bbpress plug in. We only updated wp-smush to minimise images and speed up the website.

**Comment by MSchirp** [comment]
I am noticing the bug too.

**Comment by dpatil-gmcs** [comment]
@MSchirp @lostboyevsky  We have implemented the changes required, The setting in Bootmodal Login plugin was the cause for distracted UI.
Please have a look.

**Comment by lostboyevsky** [comment]
@dpatil-gmcs, yes, this works correctly now, thanks!
