### ISSUE TITLE
Bug + Enhancement right side of recommended widget

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#244]
Hi Deepak,

Made a video!

Hope everything is clear: http://screencast.com/t/DZMfdr8IkWTX

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have made the changes and committed the code to the TEST site, Please have a look and let me know your views on it!

**Comment by dpatil-gmcs** [comment]
@MSchirp  Any Updates!

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have invested 2hrs in testing and making the user experience better, now it looks like it is as per your expectation. Please have a look, The code is committed to the TEST site.

**Comment by MSchirp** [comment]
@dpatil-gmcs This can be pushed to live!

**Comment by dpatil-gmcs** [comment]
@MSchirp  Changes are Deployed to LIVE, Tested, looks good so closing the issue!
