### ISSUE TITLE
New advertising spot 1

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#245]
I'd like a new CPC spot below the authors box on blog post pages:

This is where it should be placed, below the authors box/bio, and above the recommended articles (breaking bread, 17 videos):

![screen shot 2016-02-12 at 18 25 59](https://cloud.githubusercontent.com/assets/13124056/13014907/65bac97e-d1b6-11e5-861d-d34d388b7fd5.png)

This is what it should look like:

![cpc unit](https://cloud.githubusercontent.com/assets/13124056/13014935/89c4d292-d1b6-11e5-9db3-9b931ea6d5b0.PNG)

===

Please be aware that all advertising spots should are manually updated by me in WP-ADMIN -> HE OPTIONS. Please have a look here first @dpatil-gmcs to see how Jordan added boxes for me to do this, under **advertisement:**

![screen shot 2016-02-12 at 18 33 13](https://cloud.githubusercontent.com/assets/13124056/13015043/2d8b9438-d1b7-11e5-87a1-d507cd89244b.png)

Please add a new box here that says 'Under Author Ad Embed Code'

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have implemented the task, and committed the code to TEST site, to test it I have added the image provided by you yesterday, as the ADS will be added by you.
To test with ADs we need to deploy the code on LIVE site, but there is dependency on #244, so before we deploy the code on LIVE, Please give us a sign off for #244 so that both the codes can be deployed on LIVE site.

**Comment by dpatil-gmcs** [comment]
Please have a look and let us know your comments on it!

**Comment by dpatil-gmcs** [comment]
@MSchirp  ADs will not be displayed for obvious reasons, Please paste add related code in the HE Options and It should be good to go! Closing the issue.
Thanks!

**Comment by MSchirp** [comment]
I just added the code and the ad is not working. Please advise!

**Comment by dpatil-gmcs** [comment]
@MSchirp  I had looked at the code that you added, and I think that there is some problem with your AD related code, since I tried replacing your code with the above ad and it looked good.
I think you should replace the code with correct ad code, and the ad will be displayed!
Closing the issue!
