### ISSUE TITLE
New advertising spot 2 + 3

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#246]
For LONG blog posts ONLY, we should have a new advertising spot around 30% of reading distance and around 60% of reading distance. These ads would only show up on articles that reach a minimum size of words/distance.

@dpatil-gmcs Is reading distance calculated in lines or in characters? Or in pixel size? What would you recommend here? 

See new advertising spot 1 description to add TWO new boxes to HE OPTIONS. Namely 'Blog post 30% long post Ad Embed Code' and 'Blog post 60% long post ad embed code'

**Comment by dpatil-gmcs** [comment]
@MSchirp 

We would recommend you to use the SHORTCODE instead, because of following reasons:

1. Deciding a logical end to a statement in order to insert 30% and 60% ads needs too much of case handling and not that full fledged.

2. SHORTCODE provides you the benefits of inserting 1 small line of code via wp-admin to the Posts which we think are huge enough, that way we also logically introduce Ads.

Ex : [ads-30] / [ads-60]


Line height is something that can decide page length, but it is not guaranteed that every line in the post will have a line height defined, or any.


Please let me know your thoughts on our approach. Thanks !

**Comment by MSchirp** [comment]
1. Could you explain this point a little better?

2. I really want this to be automated. Shortcode is too much work for 750+ articles. Plus, if we ever are going to change this system, it would take double work. Are there any other variables we can use to determine an automatic spot for the new ads?

**Comment by MSchirp** [comment]
@dpatil-gmcs 

This is what Jordan had to say on the issue: "I would count the number of paragraphs and place the ad after X paragraphs (or total number of paragraphs / 3)"

Can this be a solution?

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej : We thought of this approach and we have a plugin that helps us achieve it where we can ask the plugin to insert code after a "nth" paragraph / after- before content / after - before excerpt and many other combinations. We can play around with these options...However, i don't understand why do we want to do it manually (meaning logic to identify if the post is big enough)...There may be chances that the Post has assuming 3 paragraphs but the content is large enough.

Reference URL : https://wordpress.org/plugins/ad-inserter/

Solution : 
What we can do is decide a number for the paragraph (suppose 3) after which we have to insert the Ad. This would mean the Ad will be inserted even if the paragraph content is less. And we don't have to explicitly handle these things. Does this make sense ?

**Comment by MSchirp** [comment]
Hey @dpatil-gmcs , I am not sure if I follow completely.

For example, these rules we should test out of test site first:

IF blog post is smaller than N paragraphs, don't insert any ads.
IF blog post is longer than N paragraphs, insert (in stream ad 1) after N*1/3 (rounded down) and after N*2/3 (rounded down). 

Then we can play around with the size of N to make sure all the bad scenarios don't happen. 

Thoughts? This possible with the plug in you suggested?

**Comment by dpatil-gmcs** [comment]
@MSchirp  This task is implemented on local, we are able to add the code for the ads and mention the paragraph number after which the ad must be displayed. As soon as TEST site is up, we will deploy it on TEST site.

**Comment by MSchirp** [comment]
Awesome, noted.

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have implemented the task on the TEST site, For now we have displayed the ad after the third paragraph, Please have a look and let us know your views on it so that we can deploy it on LIVE site.
Following are the steps to add the Advertisement code : 
1. In Admin panel go to  Post Adverts.
2. Click on Add new option.
3. Add the title, Ad code and the number of paragraphs after which you want to see that particular Ad.
4. Click on Publish button.

To edit the Advert :
1. Go to Post Adverts -> Post Adverts and edit the Ad you want to edit.

**Comment by MSchirp** [comment]
Hey @dpatil-gmcs Looks good!

I said on Slack:

IF blog post is smaller than N paragraphs, don't insert any ads.
IF blog post is longer than N paragraphs, insert (in stream ad 1) after N1/3 (rounded down) and after N2/3 (rounded down).

And you replied with:

dpatil [12:26 PM] 
Yes #1 is possible with plugin.
However, for #2 we can have a workaround by setting Ads for showing Ads after a particular Paragraph count.

Example : 
Rule 1 : Show Ad on N=5th paragraph.
Rule 2 : Show Ad on 8th paragraph
Rule 3 : Show Ad on 12th paragraph and so on.

------------------

I am looking for the #1 possibility in the plug in, but I can't find it. Is that within the plug in code itself?

**Comment by dpatil-gmcs** [comment]
@MSchirp  The plugin we are using is very close to our requirements. However in order to achieve the #1 possibility, we will need to understand the plugin code and modify it accordingly, Which will in turn take some time.Please le tme know your thoughts on the same.

**Comment by MSchirp** [comment]
Its very important it does #1. If not, we can't really use it. For example, lets say we want an add after 10 paragraph in articles that are bigger than 25 paragraph, we can do that. But then all articles that have 10 paragraph in total have another ad too. And that would make it very ugly.

That is why I asked in the beginning for these rules, because then we can choose N and the rest is automated and balanced. Please find a solution for the following rules:

IF blog post is smaller than N paragraphs, don't insert any ads.
IF blog post is longer than N paragraphs, insert (in stream ad 1) after N1/3 (rounded down) and after N2/3 (rounded down).

Lets say we choose N = 20. Then these rules will make sure no ads are showing for all articles with N=1-20. And on articles higher than N, lets say 21 and 30, it would show:

N = 21. Show ad after paragraph 7 and after paragraph 14. 
N = 30. Show ad after paragraph 10 and after paragraph 20.

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have implemented the code to satisfy the requirement #1, and committed the code to the TEST site.
You can set the number of paragraphs to consider for long posts in HE Options under General Settings, 
![set_longpost](https://cloud.githubusercontent.com/assets/5171153/13663918/62d8e19a-e6ca-11e5-9ed2-e313560782d4.png)

And We have also added two boxes, to add the AD code after 30% of post and after 60% of post.

![adbox](https://cloud.githubusercontent.com/assets/5171153/13663983/b7327382-e6ca-11e5-893c-b65c8b314742.png)

This will work according to the requirements.

NOTE: We are considering the length of the posts by getting number of paragraphs in the post(<p> tag). 

Please have a look and let us know your views on it.

**Comment by MSchirp** [comment]
This looks good at first sight! 

- The ads should be centred in the same manner as ATF and BTF ads. 

What do you mean exactly by: "NOTE: We are considering the length of the posts by getting number of paragraphs in the post(tag)." ? Can you elaborate on this?

**Comment by dpatil-gmcs** [comment]
@MSchirp  Looks like the ADs ATF and BTF are centered by the code you added to display the ADs in HE Options. So I think both the ads will be centered when you add the appropriate code for it.

By Note I mean that, we consider the length of post as the total number of paragraphs present in the post. By Paragraphs I mean only Paragraphs which excludes headings, Tables if any, lists etc.

**Comment by MSchirp** [comment]
@dpatil-gmcs Gocha, looks good then. Please push it to live and I will do more testing there.

**Comment by dpatil-gmcs** [comment]
@MSchirp  To deploy it on LIVE site, there is a dependency on #223. So we need to get a sign-off for #223 before we push it to LIVE.

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have deployed the code to the LIVE site.
