### ISSUE TITLE
Add a new box to HE Options

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#248]
Now we have a box called **Blog Post - Sidebar Ad Embed Code**. This one now loads the sidebar advertisement above the recommendation widget and the one below the recommendation widget. It should only load the one **above** the recommendation widget. 

For the one below please create a new box called **Blog Post - Sidebar Ad Embed Code 2**. Please add the following code to it:

```
<div class="ad-tag" data-ad-name="sidebar_2" data-ad-size="300x250" ></div>
<script src="//tags-cdn.deployads.com/a/highexistence.com.js" async ></script>
<script>(deployads = window.deployads || []).push({});</script>

```
Just deploy it to LIVE, no need to test for this one.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Implemented sidebar 2 AD and deployed the code to LIVE, Tested, It looks good so Closing the issue.
