### ISSUE TITLE
Ads not loading on AJAX pages

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#250]
Hey Deepak, I would love to find a solution to this problem. Many of our pages are loaded in AJAX (all infinite scroll pages.) Unfortunately, it seems javascript doesn't load on these pages. So advertising doesn't load either, and neither does the recommendation widget. I would love to find a way to make these pages load these ads and the recommendation widget. Can you find a solution for this?

My thoughts on this problem as a non-coder: Perhaps it is possible that when a new page is loaded in AJAX, certain parts are refreshed and loaded normal, so the javascript code can appear?

**Comment by dpatil-gmcs** [comment]
@MSchirp 
Not simple as it looks. Investing so much time in it, we found out the reason why things are not working as they should on Scroll down : 

1. Our theme is coded in such a way, that it strips off any javascript code when any POST is loaded via AJAX. Hence we are able to see ONLY THE FIRST AD and not others.
Sample URL : http://highexistence.com/beat-zen-square-zen-and-zen-a-1958-essay-by-alan-watts/
The above URL loads 'n' more Posts when scrolled down via AJAX.

2. If we ENABLE the SCRIPT LOAD option i.e. include scripts while loading Next Post, it causes regression breaks Ex : Social Media Links will be displayed as many numbers of times the POSTS are AJAX Loaded.

We will have to revisit it later with a better solution or think of ANOTHER pure HTML option for inserting Ads ex : <a><img src="" /></a>

**Comment by dpatil-gmcs** [comment]
@MSchirp  The ads issue is resolved, The code is checked in and also deployed to LIVE site, you can  test the changes on LIVE as Well as TEST site. Please have a look and let us know your comments on it!
Recommendation bar issue is yet to be solved, I will solve it under #255, As the main issue is fixed, lets close this issue!

Share Icons were also not visible for the new loaded posts, Fixed that as well!

**Comment by MSchirp** [comment]
Works like a charm, awesome! @dpatil-gmcs

**Comment by MSchirp** [comment]
I re-opened it because this also needs to be implemented on the front page! :-)

**Comment by dpatil-gmcs** [comment]
@MSchirp 
I just wanted to know, the reason for different approaches for implementating infinite scroll on home page and post pages ? 
Ex URL : 
I was looking at the code and I found that the implementation for infinite scroll is totally different,
For Post page the AJAX GET method is used to fetch new posts as we scroll down, While for home page JQuery Infinite scroll plugin is used to fetch the new listings. To make the advertisement work on home page, we need to modify the jQuery infinite scroll plugin code, which may affect some other functionaly too and is not recommended.

Please let me know your thoughts on the same, as it is always better to follow one standard approach throughout our site(Fixing it gets easier as well).

**Comment by MSchirp** [comment]
I honestly can't tell you. I am closing this issue for now because it is too high risk/low reward for now. Perhaps @jetlej can shed some light on this?
