### ISSUE TITLE
Should be able to sort through images and videos based on popularity

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#252]
I think we should have a simple option in the sidebar of the videos and image pages that allow users to filter through videos as they could in the feed version of HE. 

Thoughts on this @MSchirp @lostboyevsky ?

**Comment by lostboyevsky** [comment]
Martijn was just talking about how a user emailed us asking us to reinstate the options for filtering content by 'Best Of,' etc. i am in agreement that it would be good to reinstate these options for all content types, though i'm not sure of the best way to do it.

**Comment by MSchirp** [comment]
Please check out #187 and leave your comments/suggestions.

**Comment by MSchirp** [comment]
@JonBrooksX @lostboyevsky

**Comment by JonBrooksX** [comment]
okay
