### ISSUE TITLE
Request to send "Write for HE" submissions to different email address

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#254]
This is the "Write for HE" page:

http://highexistence.com/write-for-he/

Currently submissions are being sent to jon@highexistence.com

We want them to be sent to team@highexistence.com

**Comment by dpatil-gmcs** [comment]
@MSchirp  @JonBrooksX  This task is implemented and the code is pushed LIVE,
Please have a look and give us a sign-off so that we can close the issue.

**Comment by dpatil-gmcs** [comment]
@MSchirp @JonBrooksX  Any Updates for us?

**Comment by MSchirp** [comment]
Tested and updated, thanks!
