### ISSUE TITLE
I am no longer able to add new quotes in the backend

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#257]
I need to be able to add new quotes so that the quote on our homepage constantly changes and remains novel to our viewers. Unfortunately, the quote functionality has stopped working because of a strange bug. When I click 'Publish' on the quote submission page in the backend, the following message pops up near the 'Quote Author' box:

![screen shot 2016-02-18 at 3 45 55 pm](https://cloud.githubusercontent.com/assets/9164601/13162016/baba8c6c-d656-11e5-803d-177b93cc8c4e.png)

It is nonsensical to ask me for a URL in this slot, as this has always been a place to input the author's name and nothing more. One should only need to enter the quote text in the main text editor and then an author's name in the 'Quote Author' slot and then to hit 'Publish' to publish a quote.

**Comment by lostboyevsky** [comment]
@dpatil-gmcs any update on this? we've had the same quote on the front page for 2 weeks because i am unable to change it. @MSchirp, any thoughts?

**Comment by dpatil-gmcs** [comment]
@MSchirp : 

As this was not part of our task list based on the protocol we decided 3 weeks back, hence it was never looked upon. However, seems like this is a priority issue, hence working on it.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky : Working on it now.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky : The code is FIXED. Looking at the code seems like it never worked. It was a BUG in the QUOTE_META Meta box which was expecting a URL in place of the author name and hence it failed to publish post. Who had implemented this code ? And how was it not tested before deploying it on LIVE ?

**Comment by MSchirp** [comment]
@dpatil-gmcs Good call. We were going to remove this box with #247, however, because of a delay on our side, that was postponed too.

As I mentioned before, you are our only developer working and pushing code. So I don't know how this happened.

**Comment by dpatil-gmcs** [comment]
@MSchirp : I agree that we are the only ones developing NOW. But probably this was something implemented by the previous developers and the BUG was detected now, which was surprising. Hence my concern, that were these things not tested before they are deployed to LIVE.This code has nothing to do with our development, as we had no stories around such requirements.

**Comment by lostboyevsky** [comment]
@dpatil-gmcs, no, this bug just arose ~3 weeks ago. It was working perfectly before that. If you'll note in my opening comment, I explicitly said that the problem was that that particular field was asking for a URL instead of the author name. Previously, I was always able to enter the author's name in that field and publish quotes without a problem.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @jetlej  We only have one checkin for the file that is yesterday, Where we fix the bug.
Looking at the checkin history of the file: https://highexistence.beanstalkapp.com/highexistence/history/wp-content/themes/hethen/admin/custom-post-types.php

We found that the code is present there for a long time, and May be the feature is activated recently so found a bug.
