### ISSUE TITLE
New advertising spot 4

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#258]
On images and videos, below the top black navigation bar and above the 'more awesome posts' text, should the code of **Blog Post - Sidebar Ad Embed Code** box be placed. See screenshot:

![screen shot 2016-02-19 at 13 04 53](https://cloud.githubusercontent.com/assets/13124056/13175294/c9e26a08-d709-11e5-93b9-24146dc3e478.png)

**Comment by MSchirp** [comment]
And also on at the bottom of the recommendations, see screenshot. This one should load **Blog Post - Sidebar Ad Embed Code 2**

**Comment by dpatil-gmcs** [comment]
@MSchirp  This task is implemented and deployed on LIVE ste, Please have a look and give us a sign off so that we can close the issue!

**Comment by MSchirp** [comment]
Looks great, closing!
