### ISSUE TITLE
Install new plug in

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#259]
You can access the zip file for install here: https://s3.amazonaws.com/synthinventory/synthesis-inventory.zip

To get started, please take the following steps:

1. Download the plugin zip file linked above.
2. Install the plugin on the WordPress site(s) you are interested in moving over to Synthesis using the upload option. More information about installing plugins is available here: http://codex.wordpress.org/Managing_Plugins
3. Navigate to Tools --> "Synthesis Presale" in your WordPress Dashboard
4. Fill in the requested information and be sure to fill out your contact email address properly. (use martijn@highexistence.com)
5. Send the report directly to our support team by hitting the "Send Report" button at the bottom of the page. You can deactivate and remove the plugin after we receive your site information.
6. Let us know the information has been sent over, including the email address and domain associated with the site(s) and we will have a look and give you feedback on the best plan to fit your needs!

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have installed the plugin and sent the report as per your instructions.
For settings"Estimated Monthly Pageviews" I have put the value '1000'.
Please have a look at the attached screenshot for all the settings that were filled while sending the report.
As per your instructions I have deactivated the plugin, after the report is sent.
![synthesis_inventory_plugin_settings](https://cloud.githubusercontent.com/assets/5171153/13210502/23a720da-d956-11e5-8479-2191828f9e03.png)
