### ISSUE TITLE
Too many ads show up in recommended discussions in discussions

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#261]
Hey @dpatil-gmcs , I forgot we had an middle ad running in discussions only. This one should be de-actived across the board. See screenshot, the bottom one to the left.

![screen shot 2016-02-23 at 19 14 16](https://cloud.githubusercontent.com/assets/13124056/13261712/aaef3a6c-da61-11e5-8048-be30d5734a6e.png)

Can be found on this page: http://highexistence.com/topic/would-any-of-you-lovely-individuals-be-willing-to-share-something-with-me/

**Comment by dpatil-gmcs** [comment]
@MSchirp  This task is implemented, We have removed the middle ads in the discussion page.
The code is pushed to live site, so you can see the observe the change on the page you provided: http://highexistence.com/topic/would-any-of-you-lovely-individuals-be-willing-to-share-something-with-me/

Closing the issue.

**Comment by MSchirp** [comment]
Looks great, thanks!
