### ISSUE TITLE
Doubling of navigation bar shows up again

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#262]
See screenshot:

![screen shot 2016-02-23 at 11 13 39](https://cloud.githubusercontent.com/assets/13124056/13261995/f8249b5a-da62-11e5-85b8-6b08aafaa6d8.png)

**Comment by dpatil-gmcs** [comment]
@MSchirp  This issue is implemented and committed the code to the TEST site, The double bar doesn't appear now.
Please have a look and give us a sign-off so that we can Implemente it on LIVE site.

**Comment by MSchirp** [comment]
@dpatil-gmcs Please push it to live, I can't see the bar at all on test since it is still showing the broken homepage.

**Comment by dpatil-gmcs** [comment]
@MSchirp  This issue had a dependency on #34 to go to LIVE, So before we deploy it to LIVE we need  a signoff for the #34.

**Comment by MSchirp** [comment]
@dpatil-gmcs Please undo the dependency and push to live, thanks. #34 will take too long

**Comment by dpatil-gmcs** [comment]
@MSchirp  Ok We will do it as soon as we start working tomorrow.

**Comment by MSchirp** [comment]
Any update on this?

**Comment by dpatil-gmcs** [comment]
@MSchirp  This is pushed to LIVE, Please have a look and give us a sign-off so that we can close the issue.
