### ISSUE TITLE
Can't paste things in "Create discussion text box" without it deleting existing text

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#269]
Every time I try pasting something into a "create new discussion" box it wipes away everything that was already written in there.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX @MSchirp  We have made the changes, accordingly. Now it doesn't wipe out the content while pasting the content.

Please have a look and let us know your views on it, please give us a sign-off so that we can close the issue.

**Comment by MSchirp** [comment]
You can push this to live.

**Comment by JonBrooksX** [comment]
Great, works now!
