### ISSUE TITLE
Profile Pictures are broken.

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#27]
I try to change mine and get nothing but a blank image on Chrome and a question mark in Safari.

**Comment by jetlej** [comment]
Hmm it works fine for me. Can you try it again?

@MSchirp and @JonBrooksX - Can you change your profile image?

**Comment by MSchirp** [comment]
Works fine here. 

Btw. It seems the HE logo + text is a bit pixelated? or is that just me?

**Comment by jetlej** [comment]
lol @MSchirp, make a new issue for completely unrelated issues. It looks fine to me, but I'm on Retina
