### ISSUE TITLE
"Load more" on comments NOT working

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#270]
When I click "load more" at the bottom of the comment section nothing happens. It seems broken.

**Comment by MSchirp** [comment]
@JonBrooksX Is this in discussions or blog posts? Do you know if there are more comments to be loaded or is it just showing the load more button and it doesn't work because there are no more comments? Is it not working on all comment sections?

**Comment by JonBrooksX** [comment]
I just checked again. It was blog posts and the comments do actually load. It just takes a LONG TIME before they do. Closing for now. I guess this is a site speed issue.
