### ISSUE TITLE
Add a New 'Writing Sample' Section to the 'Write for HE' Application

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#273]
Below you'll see our current application. I would like to add another box directly below the "Link to your 3 best articles." The title of the box should be, "If you don't have any articles to link to, please insert a writing sample of at least 500 words."

Sometimes people send in writing apps and say that they don't have any articles to link to. In these cases, we need more of their writing in order to determine if they're a good fit for HE. @JonBrooksX and I agree that we no longer want to accept writers who we can't trust to write a predominantly error-free article on their own without any editing help. 

![screen shot 2016-03-15 at 3 01 02 am](https://cloud.githubusercontent.com/assets/9164601/13769975/33567e62-ea5a-11e5-869d-55f40dec6cd2.png)

**Comment by dpatil-gmcs** [comment]
@MSchirp  @lostboyevsky  We have added the 'Write sample' text area, as per your instruction, The code is committed to the TEST site. the test site Application form has the new added box.
Please have a look and let us know your views on it.

**Comment by lostboyevsky** [comment]
@dpatil-gmcs Looks good. A couple small things:

1. Inside one of the text boxes it should say "URLs only" instead of "URL's only." 
2. Inside the new text box it should say "Feel free..." instead of "Feel Free..."

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @MSchirp  We have made the changes accordingly, The code is LIVE now, you can see the code on the LIVE site. Please have a look and give us a sign-off so that we can close this issue.

I have attached the screenshot below:
![writeforhe](https://cloud.githubusercontent.com/assets/5171153/15045009/bf0edf94-12f5-11e6-928b-b9e1f14b4c63.png)

**Comment by MSchirp** [comment]
Looks good!
