### ISSUE TITLE
Post titles in the Weekly, Daily, and Monthly mail are cut short

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#274]
See the title in the screenshot. It's incomplete, ending in "...". 

I presume click through rate will increase if we can show the full title. 

![screenshot 2016-03-28 17 54 14](https://cloud.githubusercontent.com/assets/13107838/14083559/41526918-f50e-11e5-949d-02160c1a3ff1.png)

**Comment by MSchirp** [comment]
See #227
