### ISSUE TITLE
Multiple strange things are happening with the 'Sign In' function on the site

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#275]
I've noticed several problems with the 'Sign In' function in the last couple hours. I'm not sure what's going on. Some of the things it's done:

1. It's shown me that I'm not signed in, even though I am signed in.
2. If I click 'Sign In' on some pages (for instance, HE.com/blog), it just takes me to the homepage.
3. The FB button on the 'Sign In' module appeared as a square, which I believe is incorrect. 
4. I clicked 'Sign In' on the homepage, and it took me to the following page:

![screen shot 2016-03-28 at 4 14 07 pm](https://cloud.githubusercontent.com/assets/9164601/14089272/1e9bcac4-f502-11e5-9b51-b7c1c71ef2f6.png)

**Comment by MSchirp** [comment]
I've been experiencing the same issues. Sometimes, I am logged in as a different user altogether.

**Comment by MSchirp** [comment]
We also just got this e-mail, what is going on @dpatil-gmcs ?

> Hey, Great work. I recently started reading HE. I created a new account and tried to change my profile info. After i saved it, the same page kept opening with blank spaces again. After a couple of tries, a new page opened saying \'are you sure\' but without any buttons. Also i replied to a discussion which didnt get recorded. I\'m from Hyderabad, India

**Comment by dpatil-gmcs** [comment]
@MSchirp  @lostboyevsky As suggested by your server guy, We had enabled Database and Object cache. Because of which the problem occoured, We have reverted the changes and now it seems to work fine, Except the facebook icon Alignment, On which we are currently working.

**Comment by MSchirp** [comment]
According to my knowledge:

- CDN and Minification should be de-activated
- W3TC should be enabled

@jetlej & @haydenjames 

Is this correct? Are we on the same page here?

**Comment by dpatil-gmcs** [comment]
@MSchirp  @lostboyevsky   We have made the changes, now the site seems to work properly, Please have a look and let us know your views on it!

**Comment by lostboyevsky** [comment]
@dpatil-gmcs, yes, it seems to be working now, although now i'm not seeing the Facebook button *at all* when I go to sign in. It's important to get this restored ASAP, as i typically always use the FB 'sign in' function and i'm sure many others do too.

**Comment by dpatil-gmcs** [comment]
@MSchirp @lostboyevsky  Could you please give additional details, Like the browser which you are using and screen shot of the login page.
Because, at my end Facebook button is visible.

Please see the attached screen shot.
![loginform](https://cloud.githubusercontent.com/assets/5171153/14142987/69105c00-f6a6-11e5-98bf-e410e1c2d4ca.png)

**Comment by lostboyevsky** [comment]
I'm in Google Chrome on a Macbook Pro, and now I'm getting this page again when I click 'Sign In' from the HE homepage:

![screen shot 2016-03-30 at 12 19 13 pm](https://cloud.githubusercontent.com/assets/9164601/14149342/ba5598da-f671-11e5-9aeb-a6a79b7073b5.png)

When I click 'Sign In' from the he.com/blog, however, I get the correct screen --- the same one you just posted a screenshot of.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp  Can you please check it again, as I have cleared the cache and the issue is not reproducible at our end.

**Comment by lostboyevsky** [comment]
Strange things are still happening, @dpatil-gmcs. Today, when I went to HE.com, I found that it was showing I was logged in as an entirely different user who I do not know. This person: 

![screen shot 2016-03-31 at 2 55 04 pm](https://cloud.githubusercontent.com/assets/9164601/14187430/ff3c0bd4-f750-11e5-9923-43a9317dcc14.png)
![screen shot 2016-03-31 at 2 54 54 pm](https://cloud.githubusercontent.com/assets/9164601/14187431/ff40ba3a-f750-11e5-9e9c-e37820244a07.png)

I logged out and then clicked 'Sign In' from the homepage, which took me to the correct page, with the FB login working properly. However, when I clicked the FB login button, it took me back to the homepage, where it was still showing the 'Sign In' and 'Join' buttons on the navbar, instead of showing my profile image on the navbar, as it should. The profile image seems to show up on all other pages just fine, though.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky  @MSchirp  Yes, The issues was reproduced to me today for the first time. I think it is related to server side caching, @haydenjames  can you please let us know if any server side caching mechanism is used? I think for the issue #193.

**Comment by haydenjames** [comment]
The caching is w3 total cache. That would also be the only recent change.

There's PHP Opcache enabled. But that's pretter standard and does not affect how things load. The bug would most likely be related to W3 Total Cache.

Try disabling database and Object cache feature and see if that's related. Or temp disable w3 Cache completely.

**Comment by dpatil-gmcs** [comment]
@haydenjames  @lostboyevsky   @MSchirp     
I have made the necessary changes and tested at my side it looks find. I have even confirmed it with Filip.

Please have a look and let me know your views on it.

**Comment by jetlej** [comment]
Someone disabled 'Don't cache pages for logged in users' in W3TC. Also I logged in this morning and all caching was disabled.

What is going on? 

New rule: No one should be changing options for the caching plugin without asking me.

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @haydenjames @MSchirp 
As per my conversation with Filip, I came to know that the issue is observed frequently, If updating W3TC settings does not solve the issue, I will have to look at the nginx error log files.

Now the issue is not reproducible at my side. Please have a look and let me know your feed back.

**Comment by haydenjames** [comment]
What Nginx error logs? For best compatibility the server runs Apache 2.4 via cPanel build. This issue is either W3 cache or Cloudflare if any of cloudflare's settings have been changed recently. But the problem isn't before the application layer and not the HTTP stack as this does not change WordPress php code. PHP is delivered as-as via LAMP which the most well tested HTTP server stack for WordPress.

**Comment by dpatil-gmcs** [comment]
@haydenjames  @lostboyevsky  @MSchirp  Ok, We will have to look at the logs only if the problem persists again, For us the problem seems to be fixed, Please have a look and let us know your views on it.

**Comment by haydenjames** [comment]
Ok sounds good. Then it was probably W3's Object or datacache. Maybe both. You can leave as is, or toggle those cache feature to figure out which one is the culprit of not being able to cache and server correctly that dynamic content. 

**OR**
as @jetlej said, if "Don't cache pages for logged in users" was unchecked that would be the issue and as such W3 cache's features can be re-enabled to benefit fully from it's performance.

**Comment by MSchirp** [comment]
Seems to fixed.
