### ISSUE TITLE
Update mandrill with Mailchimp

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#276]
https://mandrill.zendesk.com/hc/en-us/articles/205582387-How-to-Set-up-Sending-Domains

&

https://mandrill.zendesk.com/hc/en-us/articles/217600288

**Comment by MSchirp** [comment]
Before 25 april

**Comment by MSchirp** [comment]
@dpatil-gmcs 

Can you do the following? See screenshot:

![screen shot 2016-04-27 at 18 09 35](https://cloud.githubusercontent.com/assets/13124056/14859227/81e27804-0ca3-11e6-82a4-48346532a048.png)


Instructions: https://mandrill.zendesk.com/hc/en-us/articles/205582267

https://mandrill.zendesk.com/hc/en-us/articles/205582267

**Comment by dpatil-gmcs** [comment]
@MSchirp  Our mail chimp account doesn't have any access to the madrill account,
Can you please provide us the credentials of the account which has an access to mandrill account or can you please provide admin access to our account 'gpadbidri@genius-minds.com'?
So that we can have a look into it and do the needed change.

**Comment by MSchirp** [comment]
@dpatil-gmcs Everything within Mandrill is done already, except for enabling SPF. 

`SPF

If you don't have an SPF record yet, you'll need to add one for your domain. At a minimum, the value should be the following if you're only sending mail through Mandrill for that domain:

v=spf1 include:spf.mandrillapp.com ?all
If you already have a TXT record with SPF information, you'll need to add Mandrill's servers to that record by adding include:spf.mandrillapp.com in the record (before the last operator, which is usually ?all, ~all, or -all).`

**Comment by dpatil-gmcs** [comment]
@MSchirp  We are not having access to the mandrill account. Meaning, we are unable to view the dashboard on mandrill site. Please provide us the mandrill login details so that we can login and add the required settings for SPF.

**Comment by dpatil-gmcs** [comment]
@MSchirp  The spf entry is already present, but the problem still persist,
So for this as per jordan, We should communicate with the Mandrill support.

**Comment by MSchirp** [comment]
@dpatil-gmcs @jetlej 

Here's Mandrill's response:


> Matt S. (Mandrill Support)
> May 19, 12:52 PM
> 
> Hey Jordan,
> 
> Thanks for getting in touch. It looks like the record is technically correct though you're using a record type SPF rather than the require TXT. Though some DNS providers will allow this type of record, it's generally considered deprecated and we'll require these records to be TXT type records. So you'll simply need to change the record type from SPF to TXT and you'll see this record pass as expected.
> 
> Please let me know if you have any further questions and we're glad to help.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Jordan will have to make the change, as I don't have login to the DNS server, I have asked Jordan to make the required changes on Slack.

Now waiting for his reply.

**Comment by dpatil-gmcs** [comment]
@MSchirp  The required changes have been done, I have verified on the Mandrill site and the SPF seems to be configured.
![mandrillspf](https://cloud.githubusercontent.com/assets/5171153/15501453/2d9a34fc-21cb-11e6-9759-aaa95374b8a3.png)

The issue seems to be fixed, hence closing the issue.
