### ISSUE TITLE
Limit Notifications

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#279]
If I've commented on an article or discussion I get notified whenever new people comment on that article or discussion. This is annoying, and it desensitizes you from associating importance with notifications. 

I would rather a notification only when someone directly replies to my comment. 

Exception: If you _created_ the article or discussion you should receive _all_ notifications. 

@lostboyevsky @MSchirp

**Comment by MSchirp** [comment]
See #34, I created a set of rules for notifications. Please have a look @JonBrooksX to see whether im missing something.

**Comment by JonBrooksX** [comment]
@MSchirp No, those rules look good! Closing this issue now.
