### ISSUE TITLE
Upvotes are messed up on blog posts.

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#28]
Go to HE/blog and check it. Scroll down a bit and you'll see that a bunch of posts have been reduced to just 2-5 upvotes when they used to have dozens.

**Comment by MSchirp** [comment]
Yeah, I got contacted by an author who saw his upvotes drop from 40 to 12. I just retracted my upvote and then upvoted again, now it is back to 40. See screenshots.

![screen shot 2015-07-13 at 19 19 13](https://cloud.githubusercontent.com/assets/13124056/8655896/6f51ae64-2994-11e5-9cb9-6e94b3dbfef3.png)
![screen shot 2015-07-13 at 19 19 24](https://cloud.githubusercontent.com/assets/13124056/8655897/6f6b47de-2994-11e5-8d2e-9d99c39081bc.png)

**Comment by jetlej** [comment]
@lostboyevsky - Next time you see this happening, can you immediately send me the link without fixing it first? I can't seem to duplicate the issue

**Comment by MSchirp** [comment]
You can replicate this by going to http://www.highexistence.com/blog/ , scroll down, find a blog post that has very few upvotes (like the wasp/pornography one), then upvote, refresh, and it has suddenly tons more upvotes. So upvoting them suddenly corrects the total number of votes. Perhaps use a random account to upvote all blog posts ever and it is fixed?

**Comment by MSchirp** [comment]
The upvotes from this post jumps from 20, to 180, to 4000, to 0 again. It's probably happening for other posts too.

http://www.highexistence.com/25-psychological-life-hacks-help-gain-advantage-social-situations/

**Comment by jetlej** [comment]
Closing bc we won't have upvoting anymore, woot!
