### ISSUE TITLE
Affiliate redirect plugin not working

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#287]
I'm using the thirsty affiliates plugin to turn this link:

http://jump.blinkist.com/aff_c?offer_id=15&aff_id=1715&url=https://app.blinkist.com/highexistence40%3Futm_source%3Daffiliate%26utm_medium%3Dpaid%26utm_campaign%3D20160415_HighExistence%26utm_term%3D1715%26aff_id%3D{affiliate_id}%26offer_id%3D{offer_id}%26transaction_id%3D{transaction_id}

into this link:

http://highexistence.com/recommends/40blinkistoff/

But it keeps giving me a "Page not found" result. 

@dpatil-gmcs could you look into this please? 

Typically I would try out different plugins but I don't want to take any risks with the site.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX  @MSchirp   We have made the necessary changes, and at out side the urls are redirecting to proper page, Seems like it should be fixed now.
Please have a look and give us a sign-off so that we can close the issue.
