### ISSUE TITLE
URGENT: HighExistence.com is not working in Chrome on PC

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#290]
I received this message from one of our new interns:

"I should mention I'm having a weird glitch when I visit HE on my PC using Chrome.  The website fades to the point where I can't click on anything and it says "Powered by OptinMonster" at the top, but there's no actual opt-in page, so I can't click out.  It's literally impossible for me to view anything on the site.  I thought you should know in case any other users are having this problem.  I can use Firefox with my PC and it works fine, and Chrome works fine on my MacBook.  It's just Chrome on my PC.  Really, really weird."

**Comment by MSchirp** [comment]
This should be fixed, and its not happening for me. @lostboyevsky ?

**Comment by JonBrooksX** [comment]
Yeah, this seems to be when we were running the blinkist campaign pop up. It's fixed now from what I can tell.

**Comment by lostboyevsky** [comment]
i'll ask Jason. i don't have a PC so i can't check.
