### ISSUE TITLE
Infinite scroll stopped working on the discussions page

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#291]
Scroll down on this page, it doesn't load older discussions anymore:

http://highexistence.com/discussions/ 

Please fix and push live

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have implemented the infinite scroll on the discussions page. Tested it.
Please have a look and give us a sign-off so that we can close the issue.

**Comment by MSchirp** [comment]
Looks good!
