### ISSUE TITLE
URGENT: Can't click on the above-fold discussion on the homepage for some reason.

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#292]
I'm in Chrome on my Mac. For some reason, this section at the top of the homepage is suddenly unclickable. 

![screen shot 2016-05-11 at 1 13 03 pm](https://cloud.githubusercontent.com/assets/9164601/15193321/77b14cac-177a-11e6-8c8d-6f7cd5917a74.png)

**Comment by MSchirp** [comment]
Im able to click this - is this still happening @lostboyevsky ?

**Comment by lostboyevsky** [comment]
nope, not happening anymore. not sure what that was all about
