### ISSUE TITLE
URGENT: drop-down menus on homepage glitching and some items not clickable

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#293]
The drop-down menus on the homepage are doing this weird thing where they're overlapping/blending with some of the homepage content. This looks really bad and actually renders a bunch of the drop-down buttons unclickable. See below:

![screen shot 2016-05-12 at 2 31 47 pm](https://cloud.githubusercontent.com/assets/9164601/15229553/c417eac2-184e-11e6-9351-86d7010a0475.png)

Meta-question: Why do things like this happen constantly? What is it that's being changed that is causing constant new glitches to arise? It seems like we need to develop a better protocol for ensuring that changes to the code are not going to break other things. Because, if our fixing some bugs constantly results in other bugs, then we're stuck in an endless hamster wheel of bug-fixing.

**Comment by dpatil-gmcs** [comment]
@MSchirp @lostboyevsky  We have fixed the problem and deployed the code to the LIVE site.
Please have a look and give us a sign-off so that we can close the issue.

**Comment by MSchirp** [comment]
Seems to be fixed! Do you know why this bug happened @dpatil-gmcs ?

**Comment by dpatil-gmcs** [comment]
@MSchirp  It was because of the positions of elements on the front page, some how the menu was behind the featured container.

**Comment by dpatil-gmcs** [comment]
@MSchirp  As the issue seems to be fixed, Closing the issue.
