### ISSUE TITLE
Right recommended sidebar on blog posts doesn't scroll all the way down anymore

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#294]
See screenshot:

The moment the recommended widget (Sajari) loads, the ad on the bottom right gets cut off. It worked fine before.

![screen shot 2016-05-18 at 10 48 58](https://cloud.githubusercontent.com/assets/13124056/15352808/4d9cba84-1ce6-11e6-9cda-ab7213eee65d.png)

(fyi: it still takes way too long for Sajari to load)

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have made the required changes and deployed the code to the LIVE site,
We have tested and the problem seems to be fixed.
Please have a look and give us a sign-off so that we can close the issue.

**Comment by MSchirp** [comment]
fixed!
