### ISSUE TITLE
New shortcode request

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#295]
Hey Deepak!

I would like to have a shortcode that implements an ad code wherever we place the shortcode.

Code: [psychedelic]

That code should load the advertising tags which I'd like to insert in a new box in wp-admin -> HE options -> advertisements
The new box should be called Psychedelic Advertising

Let me know if anything is not clear, thanks!

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have implemented the shortcode and deployed the code to the LIVE site. You can now add the advertisement where ever you want using the shortcode: '[psychedelic]'

Please have a look and give us a sign-off so that we can close the issue.

**Comment by MSchirp** [comment]
Im waiting on an advertiser until I can test this properly, will let you know when I do. Consider it closed for now.

**Comment by MSchirp** [comment]
So I just tested this code in the HE Options -> Psychedelic Advertising box:

`<div style="text-align:center;">
<a href="http://bit.ly/1Z8uj4v">
<img src="http://static.highexistence.com/wp-content/uploads/2016/05/HE-banner.jpg"/>
</a>
</div>`

And it didn't show properly:

![screen shot 2016-05-30 at 17 41 52](https://cloud.githubusercontent.com/assets/13124056/15653623/5cc01874-268e-11e6-9f11-416a3085cb5f.png)

It looks as if the image tag isn't closed when actually used.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Can you please give me the url of the page where you implemented it. I used the same code in a different post and the Ad seems to be displayed correctly.

Please have a look at screenshot below:
![psychedelic](https://cloud.githubusercontent.com/assets/5171153/15675940/ea79e900-2761-11e6-862f-cdc83091ee3a.png)

**Comment by MSchirp** [comment]
I used the code on this page:

http://highexistence.com/microdosing-lsd-psychedelic/

Exactly between:

Be discreet to whom you tell. Disinformation, stigma and prejudice are still mainstream.

[psychedelic]

Our Psychedelic Future

“To make this trivial world sublime, take half a gram of phanerothyme” -Huxley

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have implemented the code at the same position, It seems to be fine,

![psychedelicpost](https://cloud.githubusercontent.com/assets/5171153/15676576/6703842a-2764-11e6-9684-f6cba7f9de07.png)

**Comment by dpatil-gmcs** [comment]
@MSchirp  Any updates for us?

**Comment by MSchirp** [comment]
Not sure why the bug showed up last time, seems to work great, closing now
