### ISSUE TITLE
Discussions have been hacked / full of spam entries

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#296]
Our discussions have been hacked and have been filled with hundreds of spam discussion entries. Is there a quick way of fixing this @dpatil-gmcs or do we have to remove them all manually? 

![screenshot 2016-05-24 17 25 58](https://cloud.githubusercontent.com/assets/13107838/15501018/7c439864-21d5-11e6-8af4-0c7dbe79fd45.png)

Note: for now I've just removed "Discuss" from the nav bar to minimize exposure.

**Comment by dpatil-gmcs** [comment]
@MSchirp  @JonBrooksX  Yes, we will have to manually delete the spams, I have deleted some of them, but it is takes much time to delete the spam topics as there are many spam entries.

I think that deletion would be much easier if I get access to database.

I am also looking the way we can add the capche to the http://highexistence.com/discussions-create/ form, to prevent the robot spammers, as per @MSchirp's suggestion.

**Comment by dpatil-gmcs** [comment]
@MSchirp @JonBrooksX  
Just an FYI,
Today I have deleted all the spam topics on the site, I also found some spammers adding the spam topics over the time, Deleted the users who were adding the spams along with the spam topics they added.

To protect the spammers again, I am trying to add the captcha to the form, I have tried a couple of plugins to add the captcha but there are some minor issues with different plugins, I have added 1 such plugin to the test site, but even this plugin seems like having some problems.

I am still looking for the other ways to add the captcha to the site.

**Comment by dpatil-gmcs** [comment]
@MSchirp  @JonBrooksX  We have now implemented the captcha on the Join page and create topic page. This will protect the spam topics to be created. the create topic captch seems a bit problematic, I have researched a bit and implemented a new captcha on TEST site, Here if we use Google captcha on create discussion page we won't be able to use it on Join page.

Please have a look and let us know your thoughts on it.

**Comment by JonBrooksX** [comment]
Hi @dpatil-gmcs, 

Good work on deleting the spammers. 

I like the captcha form. Very simple and quick. 

However, I can't do a thorough test on the TEST site because I keep getting this note:

![screenshot 2016-05-31 16 17 56](https://cloud.githubusercontent.com/assets/13107838/15669640/92c10d76-274b-11e6-94ca-163d4c805bf8.png)

**Comment by MSchirp** [comment]
@JonBrooksX We already implemented a new captcha live on discussions. Will also get one on creating an account.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX  @MSchirp    Captcha on the discussions page is implemented on the LIVE site.
Please have a look. I think this must stop the spam attacks on the site, So the discussion tab can be enabled again.

To display captcha on the Join page, we are researching and working on it.

Please let me know your thoughts on it.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX  @MSchirp  Today we have researched and implented the captcha on the register page too. So now the captcha is on create topic, register user page.

Please have a look and let us know your views on it.

Just to inform you,
After adding the captcha on create topic page yesterday, the spam attack was decreased from 1000 spams to 12 spams.
I think we should observe for more couple of days after implementing captcha for register page too.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX @MSchirp  It seems like the spams are no more being added to the site, after Implementation of captcha.
I found 4 spam topics on the site, when I first logged in this week, on Monday.
It seems that these spams were entered by the humans and not bots.
I have deleted the spam topics and now after deleting it I haven't found any spam topics on the post.
I think we should wait and observe the spam entries for one more day, and close the issue if no spams found.
Please have a look and let me know your thoughts on it.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX @MSchirp Any updates for us?

**Comment by MSchirp** [comment]
I forwarded you a few mails that indicated there are some bugs with the captcha system. Please fix and report.

**Comment by haydenjames** [comment]
@JonBrooksX @MSchirp 
At the top of WP-Admin is shows that some anti-spam service that was in use previously is expired. I have no clue if related...

At the top is says:
"Please renew your anti-spam license for next year."

**Comment by dpatil-gmcs** [comment]
@JonBrooksX @MSchirp  The captcha is reimplemented and pushed to live site, Please have a look and let us know your views on it.

**Comment by dpatil-gmcs** [comment]
@JonBrooksX  @MSchirp  As per the discussion with Martijn, We have changed the font color of "Verify that you are a human." text to White and closing the issue.
