### ISSUE TITLE
Topics: When you scroll down, the suggested topic side-bar (with ads) need to scroll down too

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#297]
See topic: http://highexistence.com/topic/how-do-i-treat-others-who-think-they-are-better-than-me/

Scroll down and you will see the left side is static. This needs to automatically scroll down too. In similar fashion as to the sidebar on blog posts.

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have implemented the scroll on the discussions. I even found the same thing on the videos and Images, I have implemented the fix to these pages as well.

The code is committed to the TEST site, Please have a look and give us a sign-off so that we can deploy rhe code on LIVE.

**Comment by MSchirp** [comment]
Looks good, please push to live!

**Comment by dpatil-gmcs** [comment]
@MSchirp   Deployed the code to the LIVE site. Closing the issue!
