### ISSUE TITLE
Two new advertising spots 

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#299]
Hey Deepak

So right now in HE Options -> Advertisements we have

**Blog Post - Sidebar Ad Embed Code**
&
**Blog Post - Sidebar Ad Embed Code 2**

These bring the ad code to both blog posts AND to the left-sidebar in topics/images/videos etc (exactly the same ones as #297 ).

Since these are pages in which people reveal there own identity, google wants us to have different ads on the latter pages, the left-sidebar (not the blog post).

So the sidebar embed code for blog post stays exactly the same. The left-sidebar needs two new advertisement spots in HE Options. 

Left Sidebar Embed Code - (This one will lead to the top on the left bar)
&
Left Sidebar Embed Code 2 (this one will lead to the bottom on the left bar)

Both of them should run this code:

```
<div class="ad-tag" data-ad-name="sticky_mrec" data-ad-size="300x250" data-ad-sticky="sidebar"></div>
<script src="//tags-cdn.deployads.com/a/highexistence.com.js" async ></script>
<script>(deployads = window.deployads || []).push({});</script>
```

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have implemented the task and deployed the code to the LIVE site, and tested it.
Please have a look and give us a sign-off so that we can close the issue.

**Comment by dpatil-gmcs** [comment]
@MSchirp  Any updates for us?

**Comment by MSchirp** [comment]
Works perfectly, closing.
