### ISSUE TITLE
Strange toolbar popping up in odd place when I try to post a discussion

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#302]
When I go to post a discussion and click in the main text box, this strange extended toolbar pops up. If I scroll down the page, it moves to the bottom of the text box, concealing the text box where we enter categories for a specific post. This seems like something we don't want to happen. 

![screen shot 2016-06-13 at 10 35 40 am](https://cloud.githubusercontent.com/assets/9164601/16001981/6ac1b280-3155-11e6-89c7-e5c4ff5f2f13.png)

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @MSchirp   We have fixed the issue, now the tool bar is not visible.
The code is deployed to LIVE site, we have also tested the behaviour, the issue now seems to be fixed, 
Hence closing the issue.
