### ISSUE TITLE
Update azarius front page link

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#306]
Please change the azarius link on the frontpage below the add to:

Proudly sponsored by [logo]

[logo] =
![azarius-logo-no-icons-transparent](https://cloud.githubusercontent.com/assets/13124056/16452922/27e9c9c6-3e0b-11e6-81f0-107d37112bcf.png)

Make the size of the text 2 pt bigger and bold. Make the logo the same size as the text.

**Comment by dpatil-gmcs** [comment]
@MSchirp  I have made the required changes, Somehow I am not able to add the new images in the media library, I think either the user does not have the permissions or there is some problem occoured during the migration of the site.
The task is implemented and code is pushed to the TEST site.
For now, We have implemented the required changes on the test site and used a limage that was already  present in the media library, so you can get the rough view of the image.

Please have a look and let us know your views on it.

**Comment by MSchirp** [comment]
Looks good on live! Can you make the text a bit darker, more black? And move the text down about 2 pixels?

**Comment by dpatil-gmcs** [comment]
@MSchirp  We have made the required changes, Please have a look and give us a sign-off so that we can close the issue.
