### ISSUE TITLE
Install new plug in Imagery

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#308]
Hey Deepak, please turn off WP smush and install Imagify: 

https://downloads.wordpress.org/plugin/imagify.zip

Let me know when its done

**Comment by dpatil-gmcs** [comment]
@MSchirp  just an FYI, I have installed the plugin on activating the plugin it asks for the API key.

**Comment by MSchirp** [comment]
Thanks, Ill take it from here :)
