### ISSUE TITLE
Numbers Appearing Before Some Search Results From HE (See Images)

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#32]
![capture](https://cloud.githubusercontent.com/assets/9164601/8682182/63f95ad0-2a20-11e5-8112-0c49a7d0de67.JPG)
![capture1](https://cloud.githubusercontent.com/assets/9164601/8682183/63fd88d0-2a20-11e5-9340-335eff2324a6.JPG)

**Comment by jetlej** [comment]
Still haven't figured this one out

**Comment by lostboyevsky** [comment]
maybe @dpatil-gmcs has some idea why this would happen?

**Comment by dpatil-gmcs** [comment]
@lostboyevsky @jetlej @MSchirp Is it still reproducible? We don't see it happening, Please confirm.

**Comment by MSchirp** [comment]
@JonBrooksX Can you check if this is still happening?

**Comment by JonBrooksX** [comment]
I used to see it a lot, just did a number of searches and couldn't find it happening. Will report back if I ever see it again, but it looks fixed to me.
