### ISSUE TITLE
Notification counter doesn't get updated.

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#33]
I noticed this too lately. Now we got the following e-mail as well:

![screen shot 2015-07-14 at 22 46 26](https://cloud.githubusercontent.com/assets/13124056/8684734/4f8e36a6-2a7a-11e5-9980-0a711815ff36.png)

**Comment by jetlej** [comment]
Meaning it does not clear the notifications once you open it? Or that you have new notifications and it doesn't show an alert with the number?

**Comment by MSchirp** [comment]
This is what the user reported:

Sorry, the problem is still there, it seems very random..because at some point it does what it should..  but right now I have 1 notification, if I press the dropdown it resets to nothing (which is should) but if I then refresh the page, it returns... (same if I close the window and reopens HE)... Sorry 'bout the forth and back..

Best regards
Peter

**Comment by jetlej** [comment]
Should be fixed on live site too
