### ISSUE TITLE
Issue with "Best Of"

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#37]
When I go to Best Of > All Time and *then* click on 'Images' or 'Videos' or some other category, the site forgets that I was in Best of All Time and just goes back to the most recent images or videos. I think it should remember that other specification and show me the best of all images or videos when I navigate in this way.

**Comment by jetlej** [comment]
I thought about this when designing the site and thought it would be more annoying if people tried to navigate to the images page and were stuck in 'Best Of'.

**Comment by jetlej** [comment]
Close bc this won't be an issue with 6.0
