### ISSUE TITLE
Recommended articles still show 'contact' and 'mission'

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#4]
See title. 
![screen shot 2015-06-30 at 21 37 49](https://cloud.githubusercontent.com/assets/13124056/8440116/7d423328-1f70-11e5-9bf2-416b0e79ae5c.png)

**Comment by MSchirp** [comment]
Often the other recommended articles that are shown on the front are not the ones recommended by those on the backend.

**Comment by jetlej** [comment]
@MSchirp - What do you mean by frontend and backend not being the same? 

Can you also link to the article(s) where you see this issue?

**Comment by MSchirp** [comment]
I can't find any examples either now. It was on almost all articles the last few days however. And this issue has been recurring for very long too.

**Comment by MSchirp** [comment]
This still happens from time to time. Also on hi existence version.

**Comment by jetlej** [comment]
@MSchirp - We can remove the plugin and use a custom function if we have tags on the blog posts for gauging relevancy. Do we have tags on most posts?

**Comment by MSchirp** [comment]
Yes, we have tags on almost all posts. We can go through the ones that don’t have them too.

**Comment by jetlej** [comment]
@MSchirp - A lot of overlapping tags?

**Comment by MSchirp** [comment]
I believe so. Im not sure about our newest publications, @JonBrooksX ?

**Comment by jetlej** [comment]
I just replaced that related posts plugin with our own custom algorithm, which is 2 posts from the same category and 2 random posts from the last 20 most recent posts. 

I wasn't sure if we have good enough tagging to make it tag-dependent, so just went with categories for now.

@MSchirp @JonBrooksX
