### ISSUE TITLE
Notification leads to wrong comments section

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#46]
Just had a comment to my ayahuasca article, and it linked to this page: 

http://www.highexistence.com/ayahuasca-a-story-of-death-rebirth-and-love/comment-page-2/#comment-164862

We don't have different comment page anymore.

**Comment by jetlej** [comment]
This will be one for an outside developer to tackle. Right now we're using an infinite scroll comment system, so we can't always link directly the comment without some special coding to make sure that 'page' of comments is loaded. And I don't know why the notifications are still trying to use paged comments.

**Comment by jetlej** [comment]
@MSchirp - I think this should be a top priority for @npadbidri

**Comment by dpatil-gmcs** [comment]
@MSchirp -
Following are my queries around this task to get more clarity on it : 

1. How did you get that LINK : http://www.highexistence.com/ayahuasca-a-story-of-death-rebirth-and-love/comment-page-2/#comment-164862

2. Please provide Steps to reproduce as to what is expected from this task ?

**Comment by jetlej** [comment]
1) He got this link from a notification that someone had commented on an article of his. This results from when the blog post has so many comments that they bleed over to a second page. A good solution would be disabling paginated comments on blog posts.

**Comment by dpatil-gmcs** [comment]
@jetlej 
This task will require work efforts of 2 to 4 hours.
Will keep you posted.
Thanks..!!

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej 
1. Ensure the OPTION UNCHECKED as in the attached image : 
![selection_084](https://cloud.githubusercontent.com/assets/5171153/12171260/53d19878-b56e-11e5-9df2-207d86580020.png)

2. As you said, we can DISBALE infinit scrolling. Seems like it is already DISABLED. The Infinite Scroll Code is already commented in comments.php

**Comment by dpatil-gmcs** [comment]
@MSchirp @jetlej : I think this one is linked to #210 
Can you confirm if the issue still persists ? Thanks !

**Comment by jetlej** [comment]
@MSchirp

**Comment by MSchirp** [comment]
Seems to be fixed! @dpatil-gmcs
