### ISSUE TITLE
If you're not logged in, you can't see comments on submitted links

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#47]
First one is not logged in, same article. Second is logged in.

![screen shot 2015-07-27 at 20 14 47](https://cloud.githubusercontent.com/assets/13124056/8913927/47a3ceca-349c-11e5-8ccf-3a2707fbcec5.png)
![screen shot 2015-07-27 at 20 14 56](https://cloud.githubusercontent.com/assets/13124056/8913928/47ac9d84-349c-11e5-8a58-8c7564dee26f.png)

**Comment by jetlej** [comment]
Closing this bc links are going bye-bye!
