### ISSUE TITLE
tweets still not embedding on 6.0

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#50]
jordan, you told me tweets were embedding correctly on HE 6.0, but i'm still not seeing that on hiexistence

**Comment by jetlej** [comment]
Where are you seeing it broken?

**Comment by lostboyevsky** [comment]
here: http://hiexistence.com/13-philosophical-andor-hilariously-subversive-people-to-follow-on-twitter/

**Comment by lostboyevsky** [comment]
actually, scratch that. it's working. this one is resolved. it just takes a bit to load. i had glanced at the page for 5 seconds and they weren't showing up, but it converts them after a few seconds.
