### ISSUE TITLE
HE 6.0 dummy site so different from how it will look when launched that it's hard to judge clearly

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#51]
would it be possible to get the HE 6.0 homepage updated with all of the latest content from HE before we launch so that we can see it as it will actually look?

**Comment by jetlej** [comment]
It's filled with real content from HE. It's just old, not dummy. Why would new content be substantially different?

**Comment by lostboyevsky** [comment]
the featured images don't match up with the post titles. there are featured image images showing up in the area that's supposed to be for submitted images. it would just be cool to see the full effect. however, if this would be substantially difficult, don't worry about it.
