### ISSUE TITLE
top container above the fold on homepage doesn't pop enough

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#52]
something about the above-the-fold space on the homepage still isn't sitting quite right with me. i find my eyes being most attracted to the quotes/discussion area because of the bold purple icons against the white space. i'm not sure what we could do about this. i feel like part of the problem is that the top 3 containers with the blog posts don't pop enough. polygon is using these super deep purples and pinks that really make that top area grab your attention when you go to their site. i think the fact that their top containers span the entire width of the screen is also eye-catching. perhaps we could expand our top containers to the entire width of the screen and deepen the colors to more vibrant blues/teals/purples to make that top container really pop?

**Comment by jetlej** [comment]
What size screen are you using? I'm on a 15 inch and it spans the entire width. 

I do see your point about it popping when compared to Polygon though. We'll play around with the colors some more.

**Comment by lostboyevsky** [comment]
i'm on a big desktop at work, and it doesn't go all the way. polygon's does though. sounds good on playing around with colors. i like the font size increase on the main, large above-the-fold container. i still think that text should be squished into a narrower space though. it seems so long that my eyes don't want to skim across the whole thing

**Comment by lostboyevsky** [comment]
it's also the case on my big screen that the first blog post that is supposed to fall below the fold shows a little bit on the bottom of my screen. would be nice if this weren't the case

**Comment by jetlej** [comment]
can you screenshot what you're seeing RE: latest comment?

**Comment by jetlej** [comment]
I enhanced the colors and made it full-screen, but I don't like limiting the width of the text. Make it wrap for no reason looks strange to me. But feel free to send a screenshot of your big screen, bc all I can do is zoomout to try and see what that looks like.

**Comment by jetlej** [comment]
Before and after:

<img width="1440" alt="screen shot 2015-08-29 at 11 23 57 am" src="https://cloud.githubusercontent.com/assets/1179057/9563671/7fbcb3ea-4e40-11e5-9ef5-f8cee7f67656.png">

<img width="1440" alt="screen shot 2015-08-29 at 11 24 01 am" src="https://cloud.githubusercontent.com/assets/1179057/9563670/7fbb3754-4e40-11e5-9ac5-db0a4002fbaf.png">

**Comment by jetlej** [comment]
Btw Polygon's colors are always going to pop more bc they are pink/purple (compare the blue/green area to the purple area on ours). The colors are now equally vibrant, and have the same opacity value.

**Comment by MSchirp** [comment]
Im loving the new ‘pop’
