### ISSUE TITLE
text in top container above the fold on homepage could be better

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#53]
the other thing is the text in that top container on the homepage. i don't think it pops enough. this will be solved to some extent by a deepening of the colors in the containers. however, i still think the text in the main container could be further optimized. i think it stretches too far from side to side, making it kind of awkward to read, and i don't think it's big enough. i'd be in favor of shortening the width of the text container so that the line length is reduced and increasing the size of the text about 1.5x

**Comment by jetlej** [comment]
I made the text bigger
