### ISSUE TITLE
copy polygon's navbar idea? 

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#54]
i also really like how polygon has their navbar beneath their top container on the homepage. it's a really unique visual effect, and then it sticks to the top when you scroll down.  it might be cool to try this.

**Comment by jetlej** [comment]
Not sure on this one. I do like it bc it looks different, but it may be slightly confusing. What do ya'll think?

See it live here: http://hiexistence.com

**Comment by JonBrooksX** [comment]
Just checked it out. I don't like it with the current nav bar. Because it's the only dark thing on the page, and now it's it the middle, it makes me focus on it too much. Would you be able to lighten the nav bar background so it blends in more with the page like Polgon's does?

**Comment by jetlej** [comment]
I actually like how it stands out. We can't go white BG bc the rest of the site is white, and a lighter grey just wouldn't look good. Feel free to play around with the background color value in Chrome Developer tools. Right Click the header background and choose 'Inspect Element' and then use the style rules the popup on the right to change the color value.

**Comment by JonBrooksX** [comment]
I had a play around with it. What I liked the look of #eee as a background and the icons being black. 

What do you think about that?

**Comment by JonBrooksX** [comment]
![rough light nav bar](https://cloud.githubusercontent.com/assets/13107838/9564182/7103c6a4-4e95-11e5-8cb2-6bdb86a6c303.jpg)

**Comment by JonBrooksX** [comment]
I'm not sure, I do like the dark color too. This is just to provide a counter.

**Comment by MSchirp** [comment]
I think the black color currently live on hiex works great.

**Comment by jetlej** [comment]
So should we keep it below the top stories?

**Comment by lostboyevsky** [comment]
I'm in favor of keeping it below. I hadn't gone to the HE 6.0 site for a while and just went and felt like it really POPPED in a way that it hadn't before. I think part of that was due to the navbar change. Not sure if you also tweaked the gradients on the new blog post container, but it looks awesome.

**Comment by MSchirp** [comment]
Definitely below, haven’t seen that before but I works really well imo.
