### ISSUE TITLE
individual quote/image/video page issue -- lack of navigation to similar content

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#60]
when i click on the quote on the homepage, it takes me to a separate page displaying the same quote, but the page it takes me to doesn't have any options for 'view more quotes' or anything like that. it looks like the same is true for when i click to go to a particular image or video. i think the sidebar on these pages should suggest more quotes/images/videos, more of the same type of content. we might also want some kind of button that just says 'More Quotes' like on the homepage, taking the user to the main he.com/quotes section

**Comment by jetlej** [comment]
@lostboyevsky - Do you mean there's nothing in the sidebar to the left? Right now it's coded to only show posts from the last week. But this needs to change bc there will be no new quotes/videos/images. Should I just populate the sidebar with blog post? Or show random quotes/images/videos when you're on a quote/video/image?

**Comment by MSchirp** [comment]
The main emphasis should be on blog posts, always. So even if people go to images or videos, they should be redirect to blog posts mainly. But also have a chance to go through more videos or images, if that is what they prefer.

**Comment by lostboyevsky** [comment]
i agree that the emphasis should be on blog posts. is there a way to intersperse all types of content in the sidebar? have 3-4 blog posts along with some images and videos?

**Comment by jetlej** [comment]
Yeah we can do that. What say yee, @MSchirp and @JonBrooksX ?

**Comment by MSchirp** [comment]
sounds good to me :)

**Comment by JonBrooksX** [comment]
Agreed. I also think we should have more native ads on HE 6.0. So ads that look just like blog posts and don't stand out in a way that is unattractive.

**Comment by MSchirp** [comment]
I also like this type of content organization under a video/image/quote: http://reset.me/podcast/

**Comment by jetlej** [comment]
I'm closings this issue because it's requires the same answer as #101
