### ISSUE TITLE
2 problems with infinite scroll on individual blog posts

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#62]
re: the infinite scroll feature on individual blog posts: when i get to the bottom of a blog post, it starts me over at the exact same blog post. obviously we'd probably like it to go to a different blog post. also seeing a bug with the featured images on some posts in the infinite scroll. if the post had an image attribution (to flickr or whatever), the image attribution is showing up in the wrong spot. you can see what i mean if you go to this post (http://hiexistence.com/kill-anxiety-radically-improve-your-life-with-conscious-breathing/) and use the infinite scroll to go to the post on 'conscious breathing'

**Comment by jetlej** [comment]
That image source thing is only a problem bc that post does not have an image on the dev site. No image, no source required :)

Will fix the infinite scroll issue though
