### ISSUE TITLE
images on homepage not all the same size

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#70]
it would be nice if all images on the homepage were resized to fit in the same size containers. i don't like how this looks:

![capture](https://cloud.githubusercontent.com/assets/9164601/9503992/f067b8e6-4bee-11e5-9f5b-dc0173a5c520.JPG)

**Comment by jetlej** [comment]
Those are only going to be QOD's, which will be the same size. I could make them thumbnails, but I don't want to crop any of Jon's beautiful work.
