### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#71]
This one, where is everywhere on the site: http://www.highexistence.com/people/martijn/profile/

These random ones I found in a broken link checker: 

http://www.highexistence.com/?cat=artpoetry
http://www.highexistence.com/?cat=random-awesome
http://www.highexistence.com/?cat=elevate-yourself
http://www.highexistence.com/?cat=consciousness-meditation
http://www.highexistence.com/?cat=philosophy
http://www.highexistence.com/?cat=politics
http://www.highexistence.com/?cat=psychology-happiness
http://www.highexistence.com/?cat=science-technology

**Comment by jetlej** [comment]
The category links all work fine. It just looks similar bc it still shows the pinned posts on the category pages. 

Where do you see the link to Martijn's profile?

**Comment by jetlej** [comment]
@JonBrooksX

**Comment by JonBrooksX** [comment]
I can't find it right now. I found that link on a broken link checker. I used to see a broken link whenever /author/ was in the link (i.e. http://www.highexistence.com/author/martijn/) but now it seems that "author" has been replaced with "writer".  Maybe it was fixed and I didn't know about it.
