### ISSUE TITLE
Too much article text on blog feed

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#77]
![screenshot 2015-09-14 19 31 05](https://cloud.githubusercontent.com/assets/13107838/9858239/816e9206-5b17-11e5-9e57-1b01add4c60f.png)

**Comment by JonBrooksX** [comment]
And the tags are messed up. I'll create a new request.

**Comment by jetlej** [comment]
This is a setting that can be changed in wp-admin, you specify the character length. Martijn knows how.
