### ISSUE TITLE
"Must read" and "blog" tags and others are snipped off

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#78]
![screenshot 2015-09-14 19 30 17](https://cloud.githubusercontent.com/assets/13107838/9858280/b09b5834-5b17-11e5-8bbc-03fa165df500.png)

**Comment by jetlej** [comment]
Those tags aren't really relevant anymore since we're only post blog posts and only posting amazing content. I'm removing them.
