### ISSUE TITLE
Product widget at the bottom of the post has "review option" 

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#79]
![screenshot 2015-09-14 19 36 19](https://cloud.githubusercontent.com/assets/13107838/9858325/fa477288-5b17-11e5-9129-f318622a0144.png)

**Comment by jetlej** [comment]
which post? which site? 6.0 or live site?

**Comment by JonBrooksX** [comment]
This is in HE 6.0. All of my recent github comments were for HE 6.0.
