### ISSUE TITLE
HE 6.0: On discussion page I can't see anywhere to post a discussion

### ISSUE THREAD

**Issue by JonBrooksX** [jetlej/HE-6.0-Bugs#80]
It's not clear how to post a discussion from the discussion page. Are we cancelling this option?

**Comment by jetlej** [comment]
Good catch! Just added one. Thoughts?

<img width="1440" alt="screen shot 2015-09-15 at 9 17 32 pm" src="https://cloud.githubusercontent.com/assets/1179057/9894215/3747c00c-5bef-11e5-841f-e102a44d7f6c.png">

**Comment by JonBrooksX** [comment]
Looks great!
