### ISSUE TITLE
issue of captions on images

### ISSUE THREAD

**Issue by lostboyevsky** [jetlej/HE-6.0-Bugs#82]
i think i've mentioned this before but it was never resolved

if one adds a caption to a right-justified or left-justified image on HE, the image automatically does not allow text to stream around it. it automatically right-justifies and creates space next to it

would love to fix this

**Comment by jetlej** [comment]
It was resolved on 5.0, but not 6.0. Fixing now

**Comment by jetlej** [comment]
Whoops, it was the opposite. Now it's fixed on 5.0 :)
