### ISSUE TITLE
What do we do about following/friends?

### ISSUE THREAD

**Issue by jetlej** [jetlej/HE-6.0-Bugs#83]
Following doesn't really make sense with the new version. Not sure if it was ever really used anyways...

I'm down to do away with anything non-essential. But I could see some power users wanting to see their friends lists. Thoughts?

@lostboyevsky @MSchirp @JonBrooksX

**Comment by JonBrooksX** [comment]
Yeah following has never worked for me. 

Here are two ideas: 

1) Launch HE 6.0 but give people a week notice. 
2) Allow users to follow other users on FB from within their profile view. We don't have this feature.

I like 2.

**Comment by MSchirp** [comment]
I'd say ditch it. Unless there is an alternative that will be actually used.

**Comment by jetlej** [comment]
I tend to agree with Martijn. Might be initial blowback from a few users, but overall it's better to simplify down to what is used and what brings value

**Comment by jetlej** [comment]
Removing all references. If someone has a counter-argument, feel free to leave it here and I'll re-activate if necessary

**Comment by lostboyevsky** [comment]
i'm in agreement with that. i've never used the feature. ~40 people or so have followed me on HE maybe, but i doubt many of those people really care about the feature.
