### ISSUE TITLE
Place Azarius link in ad widget on homepage (?)

### ISSUE THREAD

**Issue by jetlej** [jetlej/HE-6.0-Bugs#85]
@MSchirp

**Comment by MSchirp** [comment]
Yes, we need to have the azarius link on the homepage. But I get a feel you're asking something else, what do you mean?

**Comment by jetlej** [comment]
I was originally asking for ideas of where to place it, but I figured it out

**Comment by MSchirp** [comment]
Can you make it a tad bigger/darker? 

(yeah yeah, I promise not to sell front page links again.)

**Comment by MSchirp** [comment]
@jetlej bump
