### ISSUE TITLE
Add 'Evolve' option to the top navigation bar and link this to the resource page

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#96]
I think the resource page shouldn't be part of a dropdown menu but rather be in full glory seen from the front page. We want to remind people as often as we can to go through this to increase our revenue.

**Comment by jetlej** [comment]
I just made it so you guys can add/edit the main nav bar in wp-admin Appearance > Menus. Just make sure you test the nav at all browser widths when you add an item. More than 3 items is too much and will break the responsive layout. You might be able to squeeze four with no icons and short titles.
