### ISSUE TITLE
Clicking on the QOD' image leads to a page where there is more than 1 image

### ISSUE THREAD

**Issue by MSchirp** [jetlej/HE-6.0-Bugs#98]
It seems it adds different images to the specific QOD. See:

http://hiexistence.com/images/view/tre-tre-tree/

&

http://hiexistence.com/images/view/love-12/

(not sure if the links are the right one either)

**Comment by jetlej** [comment]
@MSchirp -  Which QOD image? The row of three of them? Those work fine for me.

**Comment by MSchirp** [comment]
If you click on any of these:

![screen shot 2015-10-01 at 15 12 40](https://cloud.githubusercontent.com/assets/13124056/10221477/fa675e1a-684e-11e5-9e2a-47f0cfdaf01e.png)

Then I see random images on top of the QOD, like:

![screen shot 2015-10-01 at 15 13 59](https://cloud.githubusercontent.com/assets/13124056/10221501/2204806a-684f-11e5-9186-f7e1b5aa363b.png)

And:

![screen shot 2015-10-01 at 15 14 55](https://cloud.githubusercontent.com/assets/13124056/10221521/33fd83e8-684f-11e5-9a60-4d4d4e5f3752.png)

**Comment by jetlej** [comment]
This is because I changed those images after they had been submitted to QOD's. This would never occur on the live site.
